Implement window command timeouts
OpenBotsAI/OpenBots.Studio pull request #102
Opened 2021-01-28 18:06 UTC by openbots-su

2021-01-28 21:52 UTC, openbots-ff requested changes

2021-01-28 21:52 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.Window/ActivateWindowCommand.cs
> +
UIAutomationCommand and various other commands have a timeout field like this one. Please use it as a template for the v_Timeout attributes

2021-01-28 21:52 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.Window/MoveWindowCommand.cs
> +					targetWindows = User32Functions.FindTargetWindows(windowName);
Does FindTargetWindows find a window even if it is minimized? If it's minimized then it's technically not active.

2021-01-28 21:52 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.Window/MoveWindowCommand.cs
> +			List<IntPtr> targetWindows = User32Functions.FindTargetWindows(windowName);
should this be outside of the while loop as well?

2021-01-28 21:52 UTC, openbots-ch submitted a review, later dismissed

2021-01-29 14:14 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.Window/MoveWindowCommand.cs
> +					targetWindows = User32Functions.FindTargetWindows(windowName);
From my testing, it is able to find minimized windows. The window is made active and brought to the foreground upon being moved / resized.

2021-01-29 14:15 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.Window/MoveWindowCommand.cs
> +			List<IntPtr> targetWindows = User32Functions.FindTargetWindows(windowName);
Addressed in fe53ce7

2021-01-29 14:15 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.Window/ActivateWindowCommand.cs
> +
Addressed in fe53ce7

2021-01-29 14:41 UTC, openbots-ff approved these changes

2021-01-29 15:12 UTC, openbots-ch approved these changes

2021-01-29 15:15 UTC, merged