Updated HTMLInputCommand Bug#214, 215
OpenBotsAI/OpenBots.Studio pull request #113
Opened 2021-02-03 16:47 UTC by openbots-aw

- OutputVariableName will be without {} in provided HTML
- Password will be saved in secure string
- Added method to core for converting plain text (vVar1) to VariableName ({vVar1})

2021-02-03 17:32 UTC, openbots-su approved these changes

2021-02-03 19:20 UTC, openbots-ch submitted a review, later dismissed

2021-02-03 21:31 UTC, openbots-ff requested changes

2021-02-03 21:31 UTC, openbots-ff commented on OpenBots.Core/Resources/Samples/HTMLInputSample.html
> +                <input type="email" class="form-control" id="inputEmail4" v_OutputUserVariableName="vInput" placeholder="Email">
I would rather we keep the curly braces in the v_OutPutUserVariableName and remove them when the variables are processed. Otherwise this is inconsistent with how we handle outputs in general.

2021-02-03 21:44 UTC, openbots-aw commented on OpenBots.Core/Resources/Samples/HTMLInputSample.html
> +                <input type="email" class="form-control" id="inputEmail4" v_OutputUserVariableName="vInput" placeholder="Email">
But curly braces cause problem in HTML when we pass HTML string to ConvertUserVariableToString method. It places the values of variables in HTML which is not correct. Let me know if you have any suggestion to handle this otherwise.

2021-02-03 22:04 UTC, openbots-ff commented on OpenBots.Core/Resources/Samples/HTMLInputSample.html
> +                <input type="email" class="form-control" id="inputEmail4" v_OutputUserVariableName="vInput" placeholder="Email">
Resolved

2021-02-04 14:27 UTC, openbots-ff approved these changes

2021-02-04 15:04 UTC, openbots-ab approved these changes

2021-02-04 15:09 UTC, merged