project publish now autoIncrements package version Bug #179
OpenBotsAI/OpenBots.Studio pull request #114
Opened 2021-02-03 18:29 UTC by openbots-su

2021-02-03 19:29 UTC, openbots-ch submitted a review, later dismissed

2021-02-03 23:01 UTC, openbots-ff requested changes

2021-02-03 23:20 UTC, openbots-ff requested changes

2021-02-03 23:20 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmPublishProject.cs
> +        private async void frmPublishProject_Load(object sender, EventArgs e)
does the load still need to be async?

2021-02-04 14:31 UTC, openbots-su commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmPublishProject.cs
> +        private async void frmPublishProject_Load(object sender, EventArgs e)
Addressed in d8531ef

2021-02-04 14:32 UTC, openbots-su commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmPublishProject.cs
> +                    lblError.Text = "No existing package found in given directory.";
Addressed in d8531ef

2021-02-04 15:29 UTC, openbots-ab submitted a review, later dismissed

2021-02-04 15:44 UTC, openbots-ff approved these changes

2021-02-04 15:57 UTC, openbots-ch approved these changes

2021-02-04 15:57 UTC, merged