Get outlook attachments command
OpenBotsAI/OpenBots.Studio pull request #118
Opened 2021-02-05 14:33 UTC by openbots-su

2021-02-05 18:22 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Outlook/GetOutlookEmailAttachmentsCommand.cs
> +            attachmentList.StoreInUserVariable(engine, v_OutputUserVariableName);
The studio doesn't have any kind of support for Attachment types. You either need to add it to StringMethods.cs or just store a List<string> of file paths.

2021-02-05 18:22 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Outlook/GetOutlookEmailAttachmentsCommand.cs
> +            return base.GetDisplayValue() + $" [From '{v_MailItem}' - Store attachment list in '{v_OutputUserVariableName}']";
please follow capitalization conventions

2021-02-05 18:24 UTC, openbots-ff requested changes
You'll need to create a similar command for smtp/imap emails

2021-02-05 18:24 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Outlook/GetOutlookEmailAttachmentsCommand.cs
> +            attachmentList.StoreInUserVariable(engine, v_OutputUserVariableName);
The studio doesn't have any kind of support for Attachment types. You either need to add it to StringMethods.cs or just store a List of file paths.

2021-02-05 18:24 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Outlook/GetOutlookEmailAttachmentsCommand.cs
> +            return base.GetDisplayValue() + $" [From '{v_MailItem}' - Store attachment list in '{v_OutputUserVariableName}']";
please follow capitalization conventions

2021-02-05 18:37 UTC, openbots-ff requested changes

2021-02-05 18:37 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Outlook/GetOutlookEmailAttachmentsCommand.cs
> +        [Description("Specify whether to consider images in body as attachments")]
```suggestion
        [Description("Specify whether to consider images in body as attachments.")]
```

2021-02-05 18:38 UTC, openbots-ff requested changes

2021-02-05 18:38 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Outlook/GetOutlookEmailAttachmentsCommand.cs
> +        [Description("Specify whether to consider images in body as attachments")]
I can't remember if this property was missing punctuation in the get emails command (both for outlook and smtp), but if it was, it should be added there too.

2021-02-05 19:12 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Outlook/GetOutlookEmailAttachmentsCommand.cs
> +            return base.GetDisplayValue() + $" [From '{v_MailItem}' - Store attachment list in '{v_OutputUserVariableName}']";
Addressed in 572971f

2021-02-05 19:12 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Outlook/GetOutlookEmailAttachmentsCommand.cs
> +            attachmentList.StoreInUserVariable(engine, v_OutputUserVariableName);
Addressed in 572971f

2021-02-05 21:37 UTC, openbots-ff requested changes

2021-02-05 21:37 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.SystemAutomation/OpenBots.Commands.Email/GetIMAPEmailAttachmentsCommand.cs
> +        [Description("Specify whether to consider images in body as attachments")]
Punctuation again. Did you check the other files like I asked before?

2021-02-05 21:37 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Microsoft.csproj
> +    <Compile Include="OpenBots.Commands.Outlook\GetOutlookEmailAttachmentsCommand.cs" />
I don't see the IMAP command added to the SystemAutomation .csproj file.

2021-02-05 21:37 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Outlook/GetOutlookEmailAttachmentsCommand.cs
> +namespace OpenBots.Commands.Microsoft.OpenBots.Commands.Outlook
please fix the namespaces on both commands

2021-02-05 21:58 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Microsoft.csproj
> +    <Compile Include="OpenBots.Commands.Outlook\GetOutlookEmailAttachmentsCommand.cs" />
Addressed in e312a98

2021-02-05 21:58 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Outlook/GetOutlookEmailAttachmentsCommand.cs
> +namespace OpenBots.Commands.Microsoft.OpenBots.Commands.Outlook
Addressed in e312a98

2021-02-05 21:58 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.SystemAutomation/OpenBots.Commands.Email/GetIMAPEmailAttachmentsCommand.cs
> +        [Description("Specify whether to consider images in body as attachments")]
All instances are updated in e312a98

2021-02-08 04:12 UTC, openbots-ff submitted a review, later dismissed

2021-02-08 16:32 UTC, openbots-ff approved these changes

2021-02-08 16:37 UTC, openbots-ch approved these changes

2021-02-08 16:42 UTC, merged