Add continue on error option
OpenBotsAI/OpenBots.Studio pull request #120
Opened 2021-02-08 19:40 UTC by openbots-su

2021-02-08 22:05 UTC, openbots-ff approved these changes

2021-02-11 06:59 UTC, openbots-ff requested changes
This many critical changes to the engine and runtaskcommand require thorough testing of the debug tools (step in, over, continue) and the error handling (try, catch, throw etc.) commands, especially the retry command.

2021-02-11 06:59 UTC, openbots-ff commented on OpenBots.Core/UI/Controls/CustomControls/AutomationCommand.cs
> +                continueBox.Items.Add("Report Error");
the options in the debug dialog box are continue and ignore. Could we keep this consistent one way or the other?

2021-02-11 07:18 UTC, openbots-ch commented on OpenBots.Core/UI/Controls/CustomControls/AutomationCommand.cs
> +                continueBox.Items.Add("Report Error");
This change came from a discussion around intent. Continue in a debugging sense means to allow the error to bubble, while from an execution standpoint it could imply to the developer that the script will continue executing despite the error. Report error is more precise language for what is occurring with the Error Handling option, and doesn't necessarily conflict with the verbiage in the debug dialog.

2021-02-16 18:47 UTC, openbots-ch approved these changes

2021-02-18 16:23 UTC, openbots-ff approved these changes

2021-02-19 14:46 UTC, openbots-ch approved these changes

2021-02-19 15:18 UTC, openbots-ff approved these changes

2021-02-19 16:09 UTC, merged