Update tests for command consolidation
OpenBotsAI/OpenBots.Studio pull request #124
Opened 2021-02-12 19:06 UTC by openbots-su

2021-02-12 19:10 UTC, openbots-ff requested changes
In addition to fixing the test references, you also need to consolidate them as well.

2021-02-13 01:51 UTC, openbots-ff requested changes
![image](https://user-images.githubusercontent.com/51149926/107838450-ee343e80-6d73-11eb-8f70-0dcfa2353369.png)
OpenBots.Command.Core.Test is missing an 's' in Commands and DataBase should be Database

2021-02-13 01:51 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.DataManipulation.Test/OpenBots.Commands.DataManipulation.Test.csproj
> +      <EmbedInteropTypes>True</EmbedInteropTypes>
you should go through all the outlook references in each of the the projects where it exists and set the "Embed Interop Types" to false

2021-02-13 01:53 UTC, openbots-ff commented
I also noticed that the Database test project doesn't have any actual commands in it

2021-02-13 22:40 UTC, openbots-ff requested changes
It's not enough to just rename the project. You also have to rename the file directory, the AssemblyInfo.cs metadata, and the RootNamespace/AssemblyName in the .csproj.

2021-02-15 14:26 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.DataManipulation.Test/OpenBots.Commands.DataManipulation.Test.csproj
> +      <EmbedInteropTypes>True</EmbedInteropTypes>
Addressed in b3ebf74

2021-02-16 14:50 UTC, openbots-ff approved these changes

2021-02-16 18:08 UTC, openbots-ff submitted a review, later dismissed

2021-02-16 18:38 UTC, openbots-ch approved these changes

2021-02-16 18:53 UTC, openbots-ch approved these changes

2021-02-16 18:59 UTC, openbots-ff approved these changes

2021-02-16 18:59 UTC, merged