Fixed Bringing Window to Foreground
OpenBotsAI/OpenBots.Studio pull request #127
Opened 2021-02-16 15:28 UTC by openbots-ab

2021-02-16 15:55 UTC, openbots-ff requested changes

2021-02-16 15:55 UTC, openbots-ff commented on OpenBots.Core/User32/User32Functions.cs
> +            uint foreThread = GetWindowThreadProcessId(GetForegroundWindow(), IntPtr.Zero);
what was this originally used for? Does it still work?

2021-02-16 15:57 UTC, openbots-ff requested changes

2021-02-16 15:57 UTC, openbots-ff commented on OpenBots.Core/User32/User32Functions.cs
> +                BringWindowToFront(targetedWindow);
I see it used here. You're setting the windowstate in this method and overriding the state set in the switch.

2021-02-16 18:20 UTC, openbots-ab commented on OpenBots.Core/User32/User32Functions.cs
> +            uint foreThread = GetWindowThreadProcessId(GetForegroundWindow(), IntPtr.Zero);
Actually, `SetForegroundWindowNative(hWnd)` method doesn't bring a window to the front (into focus). It happens only when executing through Agent. So I replaced it with this piece of code to make it work for both Studio and Agent.

2021-02-16 18:27 UTC, openbots-ab commented on OpenBots.Core/User32/User32Functions.cs
> +                BringWindowToFront(targetedWindow);
It doesn't bring a window into focus when running through Agent.

2021-02-16 19:02 UTC, openbots-ff commented on OpenBots.Core/User32/User32Functions.cs
> +                BringWindowToFront(targetedWindow);
I understand, but you're changing the logic in the ActivateWindow method. The switch/case sets the WindowState but the BrindWindowToFront sets it to something else.

2021-02-16 19:07 UTC, openbots-ff commented on OpenBots.Core/User32/User32Functions.cs
> +                BringWindowToFront(targetedWindow);
ActivateWindow is used in the ActivateWindow command. This command determines whether a window was previously minimized, maximized, or normal and executes the appropriate step required to send the window to the front. It's different depending on what the original state was. A maximized window should stay maximized. A normal window should stay normal. Your BringWindowToFront method sets the state to Show(normal) regardless of what the original window state was. This could potentially set a maximized window to normal.

2021-02-16 19:09 UTC, openbots-ff commented on OpenBots.Core/User32/User32Functions.cs
> +                ShowWindow(hWnd, (int)WindowState.SwShow);
here

2021-02-16 19:10 UTC, openbots-ff commented on OpenBots.Core/User32/User32Functions.cs
> +                ShowWindow(hWnd, (int)WindowState.SwShow);
and here. You're hard setting the state to "Show"

2021-02-16 21:12 UTC, openbots-ff approved these changes

2021-02-16 21:26 UTC, openbots-ch approved these changes

2021-02-16 21:26 UTC, merged

2021-02-17 11:40 UTC, openbots-ab commented on OpenBots.Core/User32/User32Functions.cs
> +                BringWindowToFront(targetedWindow);
SW_SHOW flag simply activates the window and display it in its current size and position. A maximized window will remain maximized and it is so with the normal state.

For reference, please visit the following link.
[](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow)