Create And Refresh Pivot Table
OpenBotsAI/OpenBots.Studio pull request #130
Opened 2021-02-19 14:58 UTC by openbots-aw

- Added command for creating Pivot Table
- Added command for refreshing Pivot Table

2021-02-19 15:17 UTC, openbots-ff requested changes

2021-02-19 15:17 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelCreatePivotTableCommand.cs
> +        [SampleUsage("Table|| {vTable}")]
```suggestion
        [SampleUsage("Table || {vTable}")]
```

2021-02-19 15:17 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelCreatePivotTableCommand.cs
> +            return base.GetDisplayValue() + $" [Create '{v_PivotTable}' - From '{v_TableName}' -Instance Name  '{v_InstanceName}']";
```suggestion
            return base.GetDisplayValue() + $" [Create '{v_PivotTable}' From '{v_TableName}' - Instance Name  '{v_InstanceName}']";
```

2021-02-19 15:17 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelCreatePivotTableCommand.cs
> +
These spaces were added in mass by mistake when I had to delete a namespace from the entire solution, but I generally try to remove them when I see them. Please don't include them when you copy/paste code to create new commands

2021-02-19 15:17 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelCreatePivotTableCommand.cs
> +            var excelTable = workSheet.ListObjects[vTableName];
This implies that a worksheet actually contains a worksheet.ListObjects to begin with, but I don't believe we have any commands that do that. Also, at first glance, it seemed to me like the input was asking for a studio DataTable variable. Please clarify this in the description

2021-02-19 15:44 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelCreatePivotTableCommand.cs
> +            var excelTable = workSheet.ListObjects[vTableName];
worksheet.ListObjects is the list of Tables inside the excel sheet. And for creating Pivot Table sheet must contain a table from which the Pivot Table will be created. I have changed the name and description from Source Table Name to Excel Table Name.

2021-02-19 15:45 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelCreatePivotTableCommand.cs
> +
Done.

2021-02-20 04:51 UTC, openbots-ch approved these changes

2021-02-20 23:30 UTC, openbots-ff approved these changes

2021-02-20 23:30 UTC, merged