Excel Table Commands #449
OpenBotsAI/OpenBots.Studio pull request #135
Opened 2021-02-25 13:24 UTC by openbots-aw

Added Following Commands:
- ExcelCreateTableCommand
- ExcelGetTableRangeCommand
- ExcelAddTableColumnCommand
- ExcelDeleteTableColumnCommand
- ExcelSortTableCommand
- ExcelFilterTableCommand

2021-02-26 16:36 UTC, openbots-ff requested changes

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelDeleteTableColumnCommand.cs
> +    [Description("This command adds column in Excel Table.")]
```suggestion
    [Description("This command deletes a column from an Excel Table.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelDeleteTableColumnCommand.cs
> +        [DisplayName("Table Name")]
```suggestion
        [DisplayName("Excel Table Name")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelDeleteTableColumnCommand.cs
> +        [Description("Enter the name of Excel Table.")]
```suggestion
        [Description("Enter the name of the Excel Table.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelDeleteTableColumnCommand.cs
> +        [DisplayName("Excel Table Worksheet")]
```suggestion
        [DisplayName("Worksheet Name")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelDeleteTableColumnCommand.cs
> +        [Description("Enter the Worksheet name within the Workbook for deleting column from existing Table.")]
```suggestion
        [Description("Enter the name of the Worksheet containing the existing Excel Table.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelDeleteTableColumnCommand.cs
> +        [Remarks("Error will be thrown in case of invalid Sheet Name.")]
```suggestion
        [Remarks("An error will be thrown in the case of an invalid Worksheet Name.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +
please remove this empty line

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [Remarks("Error will be thrown in case of invalid Sheet Name.")]
```suggestion
        [Remarks("An error will be thrown in the case of an invalid Worksheet Name.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [DisplayName("Excel Table Worksheet")]
```suggestion
        [DisplayName("Worksheet Name")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [Description("Specify the filter list for a column to filter the table.")]
I don't really understand how this filter works at all. What should be in this list? This input also appears to be optional so it should indicate that. This means adding an (Optional) to the DisplayName attribute and removing the [Required] attribute

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [Remarks("It must be a list of type string.")]
```suggestion
        [Remarks("The filter List must be of type string.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [DisplayName("Table Name")]
```suggestion
        [DisplayName("Excel Table Name")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [Description("Enter the name of Excel Table to get Range from.")]
```suggestion
        [Description("Enter the name of the Excel Table to filter.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [Description("Enter the Worksheet name within the Workbook to filter Table.")]
```suggestion
        [Description("Enter the name of the Worksheet containing the existing Excel Table.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelGetTableRangeCommand.cs
> +    [Description("This command gets a Range of Excel Table.")]
```suggestion
    [Description("This command gets the Range of an Excel Table.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelGetTableRangeCommand.cs
> +        [DisplayName("Table Name")]
```suggestion
        [DisplayName("Excel Table Name")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelGetTableRangeCommand.cs
> +        [Description("Enter the name of Excel Table to get Range from.")]
```suggestion
        [Description("Enter the name of the Excel Table to get the Range from.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelGetTableRangeCommand.cs
> +        [DisplayName("Excel Table Worksheet")]
```suggestion
        [DisplayName("Worksheet Name")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelGetTableRangeCommand.cs
> +        [Description("Enter the Worksheet name within the Workbook to extract Range from Table.")]
```suggestion
        [Description("Enter the name of the Worksheet containing the existing Excel Table.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelGetTableRangeCommand.cs
> +        [Remarks("Error will be thrown in case of invalid Sheet Name.")]
```suggestion
        [Remarks("An error will be thrown in the case of an invalid Worksheet Name.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelSortTableCommand.cs
> +    [Description("This command Sort an Excel Table.")]
```suggestion
    [Description("This command sorts an Excel Table by the ascending or descending order of a specified column.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelSortTableCommand.cs
> +        [DisplayName("Excel Table Worksheet")]
```suggestion
        [DisplayName("Worksheet Name")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelSortTableCommand.cs
> +        [Description("Enter the Worksheet name within the Workbook to sort Table.")]
```suggestion
        [Description("Enter the name of the Worksheet containing the existing Excel Table.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelSortTableCommand.cs
> +        [Remarks("Error will be thrown in case of invalid Sheet Name.")]
```suggestion
        [Remarks("An error will be thrown in the case of an invalid Worksheet Name.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelSortTableCommand.cs
> +        [DisplayName("Table Name")]
```suggestion
        [DisplayName("Excel Table Name")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelSortTableCommand.cs
> +        [Description("Enter the name of Excel Table to get Range from.")]
```suggestion
        [Description("Enter the name of the Excel Table to sort.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelSortTableCommand.cs
> +        [DisplayName("Search Option")]
```suggestion
        [DisplayName("Column Search Option")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelSortTableCommand.cs
> +        [Description("Select whether the Table should be sorted by Column Index or Column Name.")]
```suggestion
        [Description("Select whether the column to sort the Excel Table by should be referenced by index or name.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelSortTableCommand.cs
> +        [DisplayName("Search Value")]
```suggestion
        [DisplayName("Column Search Value")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelSortTableCommand.cs
> +            return base.GetDisplayValue() + $" [Sort '{v_TableName}' by '{v_SortType}' - Instance Name  '{v_InstanceName}']";
```suggestion
            return base.GetDisplayValue() + $" [Sort '{v_TableName}' by '{v_SortType}' - Instance Name '{v_InstanceName}']";
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelGetTableRangeCommand.cs
> +            return base.GetDisplayValue() + $" [Get Range of '{v_TableName}' from '{v_SheetNameExcelTable}' - Instance Name  '{v_InstanceName}']";
```suggestion
            return base.GetDisplayValue() + $" [Get Range of '{v_TableName}' From '{v_SheetNameExcelTable}' - Instance Name '{v_InstanceName}']";
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +            return base.GetDisplayValue() + $" [Filter '{v_TableName}' by '{v_FilterList}' - Instance Name  '{v_InstanceName}']";
```suggestion
            return base.GetDisplayValue() + $" [Filter '{v_TableName}' by '{v_FilterList}' - Instance Name '{v_InstanceName}']";
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelDeleteTableColumnCommand.cs
> +            return base.GetDisplayValue() + $" [Delete '{v_DataValueIndex}' from '{v_TableName}' - Instance Name  '{v_InstanceName}']";
```suggestion
            return base.GetDisplayValue() + $" [Delete Column '{v_DataValueIndex}' From '{v_TableName}' - Instance Name '{v_InstanceName}']";
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelDeleteTableColumnCommand.cs
> +        [Description("Select whether the Table should be filtered by Column Index or Column Name.")]
```suggestion
        [Description("Select whether the column to delete from the Excel Table should be referenced by index or name.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelDeleteTableColumnCommand.cs
> +        [DisplayName("Search Option")]
```suggestion
        [DisplayName("Column Search Option")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelDeleteTableColumnCommand.cs
> +        [DisplayName("Search Value")]
```suggestion
        [DisplayName("Column Search Value")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelCreateTableCommand.cs
> +            return base.GetDisplayValue() + $" [Create '{v_TableName}' from '{v_Range}' - Instance Name  '{v_InstanceName}']";
```suggestion
            return base.GetDisplayValue() + $" [Create '{v_TableName}' From Range '{v_Range}' - Instance Name '{v_InstanceName}']";
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelCreateTableCommand.cs
> +        [Description("Enter the Range to extract data for Excel Table.")]
```suggestion
        [Description("Enter the Range to extract data from for the creation of an Excel Table.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelCreateTableCommand.cs
> +    [Description("This command creates a Excel Table.")]
```suggestion
    [Description("This command creates an Excel Table from a provided range of data.")]
```

2021-02-26 16:36 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelAddTableColumnCommand.cs
> +            return base.GetDisplayValue() + $" [Add '{v_ColumnName}' in '{v_TableName}' at '{v_ColumnIndex}' - Instance Name  '{v_InstanceName}']";
```suggestion
            return base.GetDisplayValue() + $" [Add Column '{v_ColumnName}' to Table '{v_TableName}' at Index '{v_ColumnIndex}' - Instance Name '{v_InstanceName}']";
```

2021-02-26 18:07 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelAddTableColumnCommand.cs
> +        [SampleUsage("1 || {vIndex}")]
It starts from 1.

2021-02-26 20:35 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelCreateTableCommand.cs
> +        [Description("Enter the Worksheet name within the Workbook to extract Range and create Table.")]
We discussed that for Pivot Table which is different than this one. ListObjects.Add method takes a range of cells and make it a table on the same range.

2021-02-27 21:33 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [Description("Specify the filter list for a column to filter the table.")]
User needs to provide a list of string to filter values on a column. Only values present in the list will be left after the filter and if list is empty than it will show all records. UiPath also follow this approach.
And currently we cannot provide optional in that field as user needs to provide a list, it can be empty or can have records. Let me know if you want it to be optional, I can make a change in the code.

2021-03-01 05:55 UTC, openbots-ff requested changes

2021-03-01 05:55 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelAddTableColumnCommand.cs
> +        [Remarks("Column will be added at last index if Column Index is not provided.")]
```suggestion
        [Remarks("The column will be added at the last index if a column index is not provided.")]
```

2021-03-01 05:55 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelCreateTableCommand.cs
> +        [Description("Enter the Worksheet name within the Workbook to extract Range and create Table.")]
```suggestion
        [Description("Enter the name of the Worksheet containing the Range being used to create the Excel Table.")]
```

2021-03-01 05:55 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelDeleteTableColumnCommand.cs
> +        [Description("Enter the name of the Excel Table.")]
```suggestion
        [Description("Enter the name of the existing Excel Table.")]
```

2021-03-01 05:55 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +                excelTable.Range.AutoFilter(index, Type.Missing, XlAutoFilterOperator.xlAnd, Type.Missing, Type.Missing);
This is what prompted me to believe that the filter array was optional. Why is there a null case here? On line 94, you cast the vFilterList as a List<string>, which throws an exception if the value is null. That means this case can never occur.

2021-03-01 05:55 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [Description("Specify the filter list for a column to filter the table.")]
"it can be empty" doesn't that mean it's optional?

2021-03-01 05:55 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [Description("Specify the filter list for a column to filter the table.")]
```suggestion
        [Description("Specify a List containing the values within a selected column to filter.")]
```

2021-03-01 05:55 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +    [Description("This command Filter an Excel Table.")]
```suggestion
    [Description("This command filters values from a column in an Excel Table.")]
```

2021-03-01 05:55 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [DisplayName("Search Option")]
```suggestion
        [DisplayName("Column Search Option")]
```

2021-03-01 05:55 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [DisplayName("Search Value")]
```suggestion
        [DisplayName("Column Search Value")]
```

2021-03-01 05:55 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelSortTableCommand.cs
> +        [Description("Select whether the column to sort the Excel Table by should be referenced by index or name.")]
```suggestion
        [Description("Select whether the column used to sort the Excel Table should be referenced by index or name.")]
```

2021-03-01 05:55 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +
Reminder to remove this line in case this comment was lost among all the others.

2021-03-01 10:30 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +        [Description("Specify the filter list for a column to filter the table.")]
List can be empty but not the user input, it must have the list variable.

2021-03-01 10:34 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +                excelTable.Range.AutoFilter(index, Type.Missing, XlAutoFilterOperator.xlAnd, Type.Missing, Type.Missing);
Got it, I will remove the null case. There will only be a case for empty list.

2021-03-01 10:51 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Excel/ExcelFilterTableCommand.cs
> +
Removed.

2021-03-01 13:51 UTC, openbots-ff approved these changes

2021-03-03 22:11 UTC, openbots-ch approved these changes

2021-03-03 22:11 UTC, merged