Terminal Commands
OpenBotsAI/OpenBots.Studio pull request #136
Opened 2021-02-25 21:38 UTC by openbots-ff

Terminal (Open3270) Commands and BlueZone Terminal Commands

2021-02-26 14:56 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/OpenEmulator.cs
> +        private bool IsRedrawing = false;
```suggestion
        private bool _isRedrawing = false;
```

2021-02-26 15:09 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/OpenEmulator.cs
> +        private bool IsRedrawing = false;
Please rename this private variable to `_isRedrawing`

2021-02-26 15:17 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/frmTerminal.cs
> +        private frmTerminalSettings settings = new frmTerminalSettings();
Please rename this private variable to `_frmTerminalSettings`

2021-02-26 16:39 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/OpenEmulator.cs
> +        private bool IsRedrawing = false;
done

2021-02-26 16:39 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/frmTerminal.cs
> +        private frmTerminalSettings settings = new frmTerminalSettings();
I think you meant _settings, but also done.

2021-02-26 16:41 UTC, openbots-ch requested changes

2021-02-26 16:41 UTC, openbots-ch commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/OpenEmulator.cs
> +
Might be best to adjust this to nested for readability:

```
if (GlobalHook.IsKeyDown(Keys.ShiftKey)
{
    if(GlobalHook.IsKeyToggled(Keys.Capital))
    {
        if(char.IsLetter(character))
            shift = false;
        else
            shift = true;
    }                     
    else
        shift = true;                       
} 
else
{
    if(GlobalHook.IsKeyToggled(Keys.Capital))
    {
        if(char.IsLetter(character))
            shift = true;
    }                     
    else
        shift = true;  
}
```

2021-02-26 16:41 UTC, openbots-ch commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/frmTerminalSettings.cs
> +        }
Let's go ahead and remove these values. This won't be publicly accessible.

2021-02-26 17:10 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/frmTerminalSettings.cs
> +        }
They won't be or shouldn't be? I kept them here in case I need them for development purposes

2021-02-26 17:19 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/OpenEmulator.cs
> +
I've gone ahead and implemented this, but that last shift should be false

2021-02-26 18:04 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Terminal/Library/BZTerminalContext.cs
> +        //public WhllObj BZTerminalObj { get; set; }
Please remove the comment if it's not intentional.

2021-02-26 18:04 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.BZTerminal/BZTerminalGetTextCommand.cs
> +	[Description("This command gets text from a targeted terminal screen.")]
```suggestion
	[Description("This command gets text from a specified field on a targeted terminal screen.")]
```

2021-02-26 18:05 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalPromptForPasswordCommand.cs
> +		[SampleUsage("MyBZTerminalInstance")]
Please remove the "BZ" references from the text as it's not specific to BlueZone.

2021-02-26 18:05 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalPromptForUsernameCommand.cs
> +		[SampleUsage("MyBZTerminalInstance")]
Please remove "BZ" references.

2021-02-26 18:05 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalStoreCredentialsCommand.cs
> +		[SampleUsage("MyBZTerminalInstance")]
Please remove "BZ" reference

2021-02-26 18:16 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/frmTerminal.cs
> +        private frmTerminalSettings settings = new frmTerminalSettings();
No, I meant that the name should clarify that it's a form reference.

2021-02-26 21:00 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/frmTerminal.cs
> +        private frmTerminalSettings settings = new frmTerminalSettings();
the form itself doesn't need to follow that notation. In fact, it never has.

2021-02-26 21:05 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/Library/BZTerminalContext.cs
> +        //public WhllObj BZTerminalObj { get; set; }
It is intentional. I use the actual name of the object when I hard reference the COM in development. you can see its commented out "using" at the top. Developers without BlueZone installed won't have access to that refence which is why it was necessary to create the object dynamically via an Activator.

2021-02-26 21:07 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalPromptForPasswordCommand.cs
> +		[DisplayName("BZ Terminal Instance Name")]
```suggestion
		[DisplayName("Terminal Instance Name")]
```

2021-02-26 21:08 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalPromptForPasswordCommand.cs
> +		[SampleUsage("MyBZTerminalInstance")]
```suggestion
		[SampleUsage("BZTerminalInstance")]
```

2021-02-26 21:08 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalPromptForUsernameCommand.cs
> +		[DisplayName("BZ Terminal Instance Name")]
```suggestion
		[DisplayName("Terminal Instance Name")]
```

2021-02-26 21:09 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Terminal/Library/BZTerminalContext.cs
> +        //public WhllObj BZTerminalObj { get; set; }
It's fine.

2021-02-26 21:10 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalPromptForUsernameCommand.cs
> +		[SampleUsage("MyBZTerminalInstance")]
```suggestion
		[SampleUsage("MyTerminalInstance")]
```

2021-02-26 21:10 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalStoreCredentialsCommand.cs
> +		[SampleUsage("MyBZTerminalInstance")]
```suggestion
		[SampleUsage("MyTerminalInstance")]
```

2021-02-26 21:13 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalPromptForPasswordCommand.cs
> +		[SampleUsage("MyBZTerminalInstance")]
done

2021-02-26 21:13 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalPromptForUsernameCommand.cs
> +		[SampleUsage("MyBZTerminalInstance")]
done

2021-02-26 21:13 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalStoreCredentialsCommand.cs
> +		[SampleUsage("MyBZTerminalInstance")]
done

2021-02-26 21:13 UTC, openbots-ab approved these changes

2021-02-26 21:33 UTC, openbots-ch commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/frmTerminalSettings.cs
> +        }
That machine will be de-provisioned soon. Let's remove those for now.

2021-03-01 05:58 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/Forms/frmTerminalSettings.cs
> +        }
removed

2021-03-01 06:39 UTC, openbots-ch approved these changes

2021-03-01 12:39 UTC, openbots-ab approved these changes

2021-03-03 22:11 UTC, merged