Update test output types
OpenBotsAI/OpenBots.Studio pull request #163
Opened 2021-03-09 20:16 UTC by openbots-su

2021-03-11 03:58 UTC, openbots-ff requested changes

2021-03-11 03:58 UTC, openbots-ff commented on OpenBots.Core/Utilities/CommonUtilities/VariableMethods.cs
> +        public static void CreateTestVariable(object variableValue, IAutomationEngineInstance engine, string variableName, Type variableType = null)
you can remove the comment and the "variableType = null" default as it isn't needed anymore

2021-03-11 21:48 UTC, openbots-su commented on OpenBots.Core/Utilities/CommonUtilities/VariableMethods.cs
> +        public static void CreateTestVariable(object variableValue, IAutomationEngineInstance engine, string variableName, Type variableType = null)
Addressed in 1c521aa717f5d80f417ebcfd0a65cf78ef74c7af

2021-03-11 21:50 UTC, openbots-ch approved these changes

2021-03-12 06:35 UTC, openbots-ff approved these changes

2021-03-12 06:35 UTC, merged