Trigger argument type population post-render #533
OpenBotsAI/OpenBots.Studio pull request #168
Opened 2021-03-12 19:58 UTC by openbots-su

2021-03-12 20:59 UTC, openbots-ff requested changes

2021-03-12 20:59 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/frmCommandEditor.cs
> +            SelectedCommand.Shown();
If a fix for the way a single command renders requires a change to the command editor then there needs to be another way. This could potentially create a whole host of issues for other commands.

2021-03-12 21:16 UTC, openbots-su commented on OpenBots.Studio/UI/Forms/frmCommandEditor.cs
> +            SelectedCommand.Shown();
The shown function called here is an empty virtual function in ScriptCommand. It will only run functional code if the selected command implements the Shown function from the interface. This is necessary because a command is not a form, and does not have access to form events. There is currently no other way for a command to execute code post-render until the script is run.

2021-03-12 22:18 UTC, openbots-ff requested changes

2021-03-12 22:18 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.SystemAutomation/OpenBots.Commands.Process/RunCSharpScript.cs
> +		}
We'll go with this for now but you might want to test all the other commands that show/hide controls dynamically. I feel like this wasn't happening before, or if it was we would have noticed it, but I checked UpdateAssetCommand and it's showing similar behavior. Also, command convention is to have properties, constructor, RunCommand, Render, GetDisplayValue, everything else. Please move Shown() somewhere below GetDisplayValue.

2021-03-15 13:32 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/frmCommandEditor.cs
> +            SelectedCommand.Shown();
The Render method contains controls and if you trace their Parent properties back enough, you should hit the form and its events.

2021-03-15 14:22 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.SystemAutomation/OpenBots.Commands.Process/RunCSharpScript.cs
> +		}
Addressed in 34ae689204683b90af70ca848190dbb6c0aca218

2021-03-15 19:07 UTC, openbots-ff requested changes

2021-03-15 19:07 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Server/OpenBots.Commands.Asset/UpdateAssetCommand.cs
> +			_hasRendered = false;
I don't think you need to set this? bools are usually false by default.

2021-03-15 19:07 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Server/OpenBots.Commands.Asset/UpdateAssetCommand.cs
> +		private Boolean _hasRendered;
```suggestion
		private bool _hasRendered;
```

2021-03-15 19:07 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Server/OpenBots.Commands.Asset/GetAssetCommand.cs
> +		private Boolean _hasRendered;
```suggestion
		private bool _hasRendered;
```

2021-03-15 19:07 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Server/OpenBots.Commands.Asset/GetAssetCommand.cs
> +		private Boolean _hasRendered;
visual studio throws simplification warnings if you use the long names.

2021-03-15 19:07 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Server/OpenBots.Commands.Asset/GetAssetCommand.cs
>  		}
same as the other one

2021-03-15 19:07 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalGetFieldIndexCommand.cs
> +		private Boolean _hasRendered;
```suggestion
		private bool _hasRendered;
```

2021-03-15 19:07 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalGetFieldIndexCommand.cs
> +			_hasRendered = false;
same as the other one

2021-03-16 13:47 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalGetFieldIndexCommand.cs
> +			_hasRendered = false;
Addressed in 7e19142d569289bdc93696b57b38879da6bf90f3

2021-03-16 13:47 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Server/OpenBots.Commands.Asset/GetAssetCommand.cs
>  		}
Addressed in 7e19142d569289bdc93696b57b38879da6bf90f3

2021-03-16 13:47 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Server/OpenBots.Commands.Asset/UpdateAssetCommand.cs
> +			_hasRendered = false;
Addressed in 7e19142d569289bdc93696b57b38879da6bf90f3

2021-03-16 16:53 UTC, openbots-ff approved these changes

2021-03-16 18:03 UTC, openbots-ch approved these changes

2021-03-16 18:04 UTC, merged