Remove CC and BCC as required fields
OpenBotsAI/OpenBots.Studio pull request #186
Opened 2021-03-19 21:28 UTC by openbots-su

2021-03-19 21:34 UTC, openbots-ff requested changes

2021-03-19 21:34 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Server/OpenBots.Commands.ServerEmail/SendServerEmailCommand.cs
> -        [Required]
Please add "(Optional)" to the DisplayName. Also, is the send server email request okay with leaving these blank?

2021-03-22 13:31 UTC, openbots-ch commented on OpenBots.Commands/OpenBots.Commands.Server/OpenBots.Commands.ServerEmail/SendServerEmailCommand.cs
> -        [Required]
Yes, these fields are considered optional on the API side.

2021-03-22 15:13 UTC, openbots-ff approved these changes

2021-03-22 15:16 UTC, openbots-ch approved these changes

2021-03-22 15:16 UTC, merged