Various command usability/UI fixes #592, #593
OpenBotsAI/OpenBots.Studio pull request #191
Opened 2021-03-24 17:07 UTC by openbots-su

2021-03-24 18:07 UTC, openbots-ff requested changes

2021-03-24 18:07 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Server/OpenBots.Commands.Asset/UpdateAssetCommand.cs
> +			AssetTypeComboBox_SelectedValueChanged(this, null);
Could you rename these methods to "_SelectedIndexChanged" since that's the event handler being used here? I saw this in other files as well.

2021-03-24 18:07 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalGetFieldIndexCommand.cs
> +			searchOptionComboBox_SelectedValueChanged(this, null);
please delete the foreach on line 142 and 150 as well if they aren't needed

2021-03-24 18:24 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Server/OpenBots.Commands.Asset/UpdateAssetCommand.cs
> +			AssetTypeComboBox_SelectedValueChanged(this, null);
Addressed in 6a80dbc3436d314aeafc7f934d7439f53e2477b1

2021-03-24 18:24 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Terminal/OpenBots.Commands.Terminal/TerminalGetFieldIndexCommand.cs
> +			searchOptionComboBox_SelectedValueChanged(this, null);
Addressed in 6a80dbc3436d314aeafc7f934d7439f53e2477b1

2021-03-24 18:59 UTC, openbots-ff approved these changes

2021-03-25 18:40 UTC, openbots-ff approved these changes

2021-03-25 19:01 UTC, openbots-ch approved these changes

2021-03-25 19:01 UTC, merged