All Remaining Command Cleanup
OpenBotsAI/OpenBots.Studio pull request #2
Opened 2020-08-25 21:48 UTC by openbots-ff

Cleanup:
- DataBase Commands
- Engine Commands
- Input Commands
- Misc Commands
- NLG Commands
- Regex Commands
- Remote Commands
- System Commands
- Window Commands

Added new CommandsControls:
- CreateDefaultPasswordInputGroupFor - Hides text typed into TextBoxes by replacing it with '*'. Used primarily for password inputs. 
- CreateDefaultWindowControlGroupFor - Dropdown that generates all currently open windows. Used frequently in window and input commands.

2020-08-27 21:59 UTC, openbots-ab commented on taskt.Commands/Data Commands/DateCalculationCommand.cs
> +                operand = v_CalculationMethod.Replace(interval, "").TrimEnd();//$"{v_CalculationMethod.Split(' ')[0]} {v_CalculationMethod.Split(' ')[1]}";
Please remove the comment.

2020-08-27 22:00 UTC, openbots-ab commented on taskt.Commands/Database Commands/DefineDatabaseConnectionCommand.cs
> +        [SampleUsage("myRobot || {vUsername}")]
```suggestion
        [SampleUsage("Provider=sqloledb;Data Source=myServerAddress;Initial Catalog=myDataBase;Integrated Security=SSPI; || {vConnectionString}")]
```

2020-08-27 22:02 UTC, openbots-ab commented on taskt.Commands/Regex Commands/RegexIsMatchCommand.cs
> +        [InputSpecification("Enter a Regex Pattern to apply to Input Text to get all the matches.")]
```suggestion
        [InputSpecification("Enter a Regex Pattern to apply to the Input Text.")]
```

2020-08-27 22:02 UTC, openbots-ab commented on taskt.Commands/Regex Commands/RegexReplaceCommand.cs
> +    [Description("This command replaces all the matches in a given text based on a Regex pattern")]
```suggestion
    [Description("This command replaces all the matches in a given text based on a Regex pattern.")]
```

2020-08-27 22:03 UTC, openbots-ab commented on taskt.Commands/Regex Commands/RegexReplaceCommand.cs
> +        [InputSpecification("Enter a Regex Pattern to apply to Input Text to get all the matches.")]
```suggestion
        [InputSpecification("Enter a Regex Pattern to apply to the Input Text.")]
```

2020-08-27 22:03 UTC, openbots-ab commented on taskt.Commands/Regex Commands/RegexSplitCommand.cs
> +        [InputSpecification("Enter a Regex Pattern to apply to Input Text to get all the matches.")]
```suggestion
        [InputSpecification("Enter a Regex Pattern to apply to the Input Text.")]
```

2020-08-27 22:03 UTC, openbots-ab commented on taskt.Commands/Remote Commands/RemoteAPICommand.cs
> +        [InputSpecification("Select the appropriate parameter.")]
```suggestion
        [InputSpecification("Select the appropriate parameter type.")]
```

2020-08-27 22:04 UTC, openbots-ab commented on taskt.Commands/Remote Commands/RemoteTaskCommand.cs
> +        [InputSpecification("Select the appropriate parameter.")]
```suggestion
        [InputSpecification("Select the appropriate parameter type.")]
```

2020-08-27 22:04 UTC, openbots-ab commented on taskt.Commands/System Commands/EnvironmentVariableCommand.cs
> +    [Description("This command exclusively selects a environment variable.")]
```suggestion
    [Description("This command exclusively selects an environment variable.")]
```

2020-08-27 22:05 UTC, openbots-ab commented on taskt.Commands/System Commands/LaunchRemoteDesktopCommand.cs
> +    [Description("This command allows you to launch a remote desktop session.")]
```suggestion
    [Description("This command launches a remote desktop session.")]
```

2020-08-27 22:05 UTC, openbots-ab commented on taskt.Commands/System Commands/LaunchRemoteDesktopCommand.cs
>          [SampleUsage("")]
Please provide Sample Usage.

2020-08-27 22:06 UTC, openbots-ab commented on taskt.Studio/Commands/Engine Commands/SetEnginePreferenceCommand.cs
> +    [Description("This command allows you to set preferences for engine behavior at runtime.")]
```suggestion
    [Description("This command sets preferences for engine behavior at runtime.")]
```

2020-08-27 22:06 UTC, openbots-ab commented on taskt.Studio/Commands/Engine Commands/SetEnginePreferenceCommand.cs
> +            return base.GetDisplayValue() + $" [Calculation '{v_CalculationOption}']";
I think it should simply be
```suggestion
            return base.GetDisplayValue() + $" [To '{v_CalculationOption}']";
```

2020-08-27 22:07 UTC, openbots-ab commented on taskt.Studio/Commands/Window Commands/SetWindowStateCommand.cs
> +            RenderedControls.Add(CommandControls.CreateDropdownFor("v_WindowState", this));
You can use CreateDefaultDropDownGroupFor method here.

2020-08-27 22:07 UTC, openbots-ab commented on taskt.Studio/Commands/Window Commands/WaitForWindowToExistCommand.cs
> +            return base.GetDisplayValue() + $" [ Window '{v_WindowName}' - Timeout '{v_Timeout}']";
```suggestion
            return base.GetDisplayValue() + $" [Window '{v_WindowName}' - Timeout '{v_Timeout}']";
```

2020-08-27 22:11 UTC, openbots-ab approved these changes

2020-08-27 22:12 UTC, openbots-ab requested changes
Please make a bunch of requested changes.

2020-08-28 01:52 UTC, openbots-ff commented on taskt.Studio/Commands/Engine Commands/SetEnginePreferenceCommand.cs
> +            return base.GetDisplayValue() + $" [Calculation '{v_CalculationOption}']";
I think this command was intended to allow the user to set multiple engine preferences at runtime, but currently the only one available is the option to allow math to be done on variables. That's why using "To" would be too vague.

2020-08-28 01:57 UTC, openbots-ff commented on taskt.Studio/Commands/Window Commands/SetWindowStateCommand.cs
> +            RenderedControls.Add(CommandControls.CreateDropdownFor("v_WindowState", this));
done

2020-08-28 01:58 UTC, openbots-ff commented on taskt.Commands/System Commands/LaunchRemoteDesktopCommand.cs
>          [SampleUsage("")]
done

2020-08-28 01:59 UTC, openbots-ff commented on taskt.Commands/Data Commands/DateCalculationCommand.cs
> +                operand = v_CalculationMethod.Replace(interval, "").TrimEnd();//$"{v_CalculationMethod.Split(' ')[0]} {v_CalculationMethod.Split(' ')[1]}";
done

2020-08-28 10:44 UTC, openbots-ab commented on taskt.Studio/Commands/Engine Commands/SetEnginePreferenceCommand.cs
> +            return base.GetDisplayValue() + $" [Calculation '{v_CalculationOption}']";
Then it's fine.

2020-08-28 11:00 UTC, openbots-ab approved these changes

2020-08-28 13:35 UTC, merged