Project Arguments
OpenBotsAI/OpenBots.Studio pull request #209
Opened 2021-04-06 18:25 UTC by openbots-ff

Implemented project arguments that are serialized in project.obconfig and function when running python, tagui, and csscript "Main" scripts only. When projects are published to the server, arguments are published as well.

2021-04-07 02:49 UTC, openbots-ch submitted a review, later dismissed

2021-04-08 14:47 UTC, openbots-ab requested changes

2021-04-08 14:47 UTC, openbots-ab commented on OpenBots.Studio/Utilities/ExecutionManager.cs
> +            var test = mainMethod.GetParameters();
Please remove this line as it seems like `test` variable is not being used in this block.

2021-04-08 14:52 UTC, openbots-ff commented on OpenBots.Studio/Utilities/ExecutionManager.cs
> +            var test = mainMethod.GetParameters();
```suggestion
```

2021-04-08 14:53 UTC, openbots-ff commented on OpenBots.Studio/Utilities/ExecutionManager.cs
> +            var test = mainMethod.GetParameters();
done

2021-04-08 14:56 UTC, openbots-ab approved these changes

2021-04-08 15:21 UTC, openbots-ch approved these changes

2021-04-08 15:21 UTC, merged