Integrate Roslyn code evaluation and variables
OpenBotsAI/OpenBots.Studio pull request #213
Opened 2021-04-08 16:44 UTC by openbots-su

2021-04-12 07:07 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Core/OpenBots.Commands.Engine/PauseScriptCommand.cs
>  			var pauseLength = int.Parse(userPauseLength);
these two lines should be merged. The user should provide an int, not a string that's parsed as an int

2021-04-12 08:01 UTC, openbots-ff requested changes

2021-04-12 08:01 UTC, openbots-ff commented on OpenBots.Studio/UI/CustomControls/CommandControls.cs
> +            //variableNameControl.Click += (sender, e) => VariableNameControl_Click(sender, e, editor);
please uncomment these

2021-04-23 21:42 UTC, openbots-ff approved these changes

2021-04-23 21:44 UTC, openbots-ch approved these changes

2021-04-23 21:44 UTC, merged