Feedback Modification
OpenBotsAI/OpenBots.Studio pull request #23
Opened 2020-09-23 02:23 UTC by openbots-ff

- Breakpoint button for commands 
- Hotkeys for breakpoint/enable/disable commands 
- Hotkeys for project tool strip menu 
- Clarification for creating vs writing to text files 
- Clear search button for command search box 
- Support for Dictionaries in debug 
- Search bars for Variable and Element Selectors 
- Deleting enclosing commands such as "BeginLoop" will delete all commands up to the respective End command.

2020-09-23 03:04 UTC, openbots-ch commented on OpenBots.Commands/OpenBots.Commands.List/CreateListCommand.cs
> -            if (!string.IsNullOrEmpty(v_ListItems.Trim()))
Was trimming empty strings causing issues for this check? I would assume it lets you trim the spaces out of a technically blank string for asserting empty.

2020-09-23 03:23 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.List/CreateListCommand.cs
> -            if (!string.IsNullOrEmpty(v_ListItems.Trim()))
it turns out that if left empty, the default value is null. And you can't trim null.

2020-09-23 04:21 UTC, openbots-ch requested changes

2020-09-23 04:21 UTC, openbots-ch commented on OpenBots.Studio/Commands/Input Commands/UIAutomationCommand.cs
> +            frmAdvancedUIElementRecorder newElementRecorder = new frmAdvancedUIElementRecorder();
Will this still work cleanly for single element grabbing, or will it go for a sequence every time?

2020-09-23 14:01 UTC, openbots-ff commented on OpenBots.Studio/Commands/Input Commands/UIAutomationCommand.cs
> +            frmAdvancedUIElementRecorder newElementRecorder = new frmAdvancedUIElementRecorder();
Yes, there's a flag that sets it

2020-09-23 14:41 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Outlook/GetOutlookEmailsCommand.cs
> +        [XmlIgnore]
done

2020-09-23 19:37 UTC, openbots-ch submitted a review, later dismissed

2020-09-28 15:18 UTC, openbots-ch approved these changes

2020-09-28 16:54 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Word/WordCreateApplicationCommand.cs
> +            if (((ComboBox)RenderedControls[3]).Text == "Open Workbook")
```suggestion
            if (((ComboBox)RenderedControls[3]).Text == "Open Document")
```

2020-09-28 16:55 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.TextFile/WriteTextFileCommand.cs
> +    public class WriteCreateTextFileCommand : ScriptCommand
Please update the File name to match with the Class name.

2020-09-28 16:56 UTC, openbots-ab requested changes
A couple of changes need to be made.

2020-09-28 17:01 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.TextFile/WriteTextFileCommand.cs
> +    public class WriteCreateTextFileCommand : ScriptCommand
done

2020-09-28 17:07 UTC, openbots-ab approved these changes

2020-09-28 17:24 UTC, openbots-ch approved these changes

2020-09-28 18:14 UTC, merged