Use SecureString for passwords in DB commands
OpenBotsAI/OpenBots.Studio pull request #230
Opened 2021-04-26 19:45 UTC by openbots-su

2021-04-26 21:01 UTC, openbots-ch submitted a review, later dismissed

2021-04-28 13:54 UTC, openbots-ff requested changes

2021-04-28 13:54 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Database/DefineDatabaseConnectionCommand.cs
>  			_connectionStringPassword = commandControls.CreateDefaultInputFor("v_ConnectionStringPassword", this);
this still needs to be one Inputgroup

2021-04-28 13:55 UTC, openbots-ff requested changes

2021-04-28 13:55 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Database/DefineDatabaseConnectionCommand.cs
>  			label.Text = "NOTE: If storing the password in the textbox below, please ensure the connection string " +
you can move this warning to the Remarks

2021-04-28 14:39 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Database/DefineDatabaseConnectionCommand.cs
>  			_connectionStringPassword = commandControls.CreateDefaultInputFor("v_ConnectionStringPassword", this);
Addressed in 
d25261a

2021-04-28 14:40 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Database/DefineDatabaseConnectionCommand.cs
>  			label.Text = "NOTE: If storing the password in the textbox below, please ensure the connection string " +
Addressed in 
d25261a

2021-04-28 19:00 UTC, openbots-ff submitted a review, later dismissed

2021-04-29 14:52 UTC, openbots-ff approved these changes

2021-04-29 16:49 UTC, openbots-ch approved these changes

2021-04-29 16:49 UTC, merged