Studio UI Roslyn Implementation + Validation
OpenBotsAI/OpenBots.Studio pull request #239
Opened 2021-05-04 20:51 UTC by openbots-ff

2021-05-04 20:59 UTC, openbots-ff commented on OpenBots.Studio/UI/CustomControls/CommandControls.cs
> +            //editor.ScriptEngineContext.Container = _container;
```suggestion
```

2021-05-04 22:10 UTC, openbots-ab requested changes

2021-05-04 22:10 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/ScriptBuilder Forms/frmScriptBuilderListView.cs
> +                //_scriptContext.ImportedNamespaces = newSequence.ImportedNamespaces;
Please remove these commented lines if not required

2021-05-04 22:10 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Sequence Forms/frmSequenceVariableArgument.cs
>                      CodeDomProvider provider = CodeDomProvider.CreateProvider("C#");
Please remove line 55 as provider is already defined.

2021-05-04 22:13 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/Sequence Forms/frmSequenceVariableArgument.cs
>                      CodeDomProvider provider = CodeDomProvider.CreateProvider("C#");
done

2021-05-04 22:17 UTC, openbots-ab approved these changes

2021-05-05 15:38 UTC, openbots-ch approved these changes

2021-05-05 15:38 UTC, merged