OpenBots.Core Cleanup
OpenBotsAI/OpenBots.Studio pull request #24
Opened 2020-09-23 21:12 UTC by openbots-ch

2020-09-24 13:27 UTC, openbots-ff requested changes

2020-09-24 13:27 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.System/LaunchRemoteDesktopCommand.cs
> +            displayManager.Close();
You seem to be opening and closing this form without actually returning anything.

2020-09-24 13:27 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/frmSettings.cs
> +        //private void btnLaunchDisplayManager_Click(object sender, EventArgs e)
remove leftover comment?

2020-09-28 13:12 UTC, openbots-ff requested changes

2020-09-28 13:12 UTC, openbots-ff commented on OpenBots.Core/IO/JavaInterface.cs
>              var jarLibary = Path.Combine(Path.GetDirectoryName(Application.ExecutablePath), "Resources", jarName);
I believe this path will point to the bin directory in the openbots.studio project, but the .jar resource you're using is located in the command resources. Is this working?

2020-09-28 13:17 UTC, openbots-ff approved these changes

2020-09-28 13:22 UTC, openbots-ch commented on OpenBots.Studio/UI/Forms/frmSettings.cs
> +        //private void btnLaunchDisplayManager_Click(object sender, EventArgs e)
done

2020-09-28 13:23 UTC, openbots-ch commented on OpenBots.Commands/OpenBots.Commands.System/LaunchRemoteDesktopCommand.cs
> +            displayManager.Close();
Will be fixed in a second PR. The manager itself isn't particularly useful at the moment in general.

2020-09-28 13:28 UTC, openbots-ff approved these changes

2020-09-28 13:44 UTC, openbots-ab commented on OpenBots.Studio/Utilities/GlobalHook.cs
> +                    _ = GetWindowText(winHandle, _buffer, _buffer.Capacity);
Can you please check this?

2020-09-28 13:46 UTC, openbots-ab requested changes
I left a comment for you, please check.

2020-09-28 13:47 UTC, openbots-ch commented on OpenBots.Core/IO/JavaInterface.cs
>              var jarLibary = Path.Combine(Path.GetDirectoryName(Application.ExecutablePath), "Resources", jarName);
We can come back on this. The command isnt working on 1.0.4 either, and we should probably eliminate the jar method altogether.

2020-09-28 13:47 UTC, openbots-ch commented on OpenBots.Studio/Utilities/GlobalHook.cs
> +                    _ = GetWindowText(winHandle, _buffer, _buffer.Capacity);
Just replaced the length variable with a discard since we weren't using the created length variable.

2020-09-28 13:49 UTC, openbots-ab approved these changes

2020-09-28 13:49 UTC, merged