Open Source Server SDK Implementation
OpenBotsAI/OpenBots.Studio pull request #240
Opened 2021-05-04 21:44 UTC by openbots-nc

- Refactor all server methods/commands to ensure they work with the Server SDK
  - Asset Methods / Commands
  - Automation Methods
  - Auth Methods
  - Credential Methods / Commands
  - Server Email Methods / Commands
  - Queue Methods
  - Queue Item Methods / Commands

2021-05-05 11:12 UTC, openbots-ff requested changes

2021-05-05 11:12 UTC, openbots-ff commented on OpenBots.Core/Server/API Methods/AuthMethods.cs
> +                    Address = "https://dev.login.openbots.io/connect/token", //TODO: use server url??
@openbots-ab Will these credentials be in the same settings file?

2021-05-05 11:12 UTC, openbots-ff commented on OpenBots.Core/Server/API Methods/CredentialMethods.cs
> +                var credentialSDK = JsonConvert.DeserializeObject<OpenBots.Server.SDK.Model.Credential>(credentialJson);
please shorten the namespace before Credential

2021-05-05 11:12 UTC, openbots-ff commented on OpenBots.Core/Server/Models/Asset.cs
> +        public Guid? FileId { get; set; }
Do we still need these models if the SDK has them?

2021-05-05 11:12 UTC, openbots-ff commented on OpenBots.Core/Server/User/EnvironmentSettings.cs
> +        public static string serverURL = settings["OpenBotsServerUrl"];
won't this throw an exception if settings is null?

2021-05-05 11:13 UTC, openbots-ff commented
When you feel like the SDK is ready, please upload it to the gallery and check the "Official" and "Command" checkboxes

2021-05-05 17:08 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.SystemAutomation.Test/app.config
> +        <assemblyIdentity name="System.Text.Encodings.Web" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
No, it's only added in Core. I will remove the dependencies for each project

2021-05-05 17:20 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Microsoft.csproj
> -    <COMReference Include="Microsoft.Office.Core">
No idea.  Adding it back in now.

2021-05-05 17:52 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Microsoft.csproj
> -    <COMReference Include="Microsoft.Office.Core">
It doesn't look like it is being referenced anywhere.  Can I keep it as is or try to add it back in?

2021-05-05 18:09 UTC, openbots-nc commented on OpenBots.Core/Server/API Methods/AuthMethods.cs
> +                    Address = "https://dev.login.openbots.io/connect/token", //TODO: use server url??
Eventually once the Agent is changed to work with both the cloud Server and open source Server, yes.  I can share with you the notes that Ashish gave me so we are all on the same page.

2021-05-05 18:12 UTC, openbots-nc commented on OpenBots.Core/Server/Models/Asset.cs
> +        public Guid? FileId { get; set; }
Not sure.  I will try removing them and see if the SDK still works without them.

2021-05-05 18:13 UTC, openbots-nc commented on OpenBots.Core/Server/User/EnvironmentSettings.cs
> +        public static string serverURL = settings["OpenBotsServerUrl"];
Yes, but wouldn't that mean the Agent isn't connected?

2021-05-05 18:57 UTC, openbots-nc commented on OpenBots.Core/Server/Models/Asset.cs
> +        public Guid? FileId { get; set; }
When I switched the credential model over, I faced an issue when trying to run the GetCredentialCommand in the parentCommand.RunCommand(this) on line 490 of AutomationEngineInstance: "Method not found: 'OpenBots.Server.SDK.Model.Credential OpenBots.Core.Server.API_Methods.CredentialMethods.GetCredential(System.String, System.String)'."

2021-05-05 19:03 UTC, openbots-nc commented on OpenBots.Core/Server/Models/Asset.cs
> +        public Guid? FileId { get; set; }
When switching the model over from Studio to Server.SDK, I get this error when trying to get a credential in the parentCommand.RunCommand(this) method on line 490 of AutomationEngineInstance: {"Method not found: 'OpenBots.Server.SDK.Model.Credential OpenBots.Core.Server.API_Methods.CredentialMethods.GetCredential(System.String, System.String)'."}

2021-05-05 19:14 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.SystemAutomation.Test/app.config
> +        <assemblyIdentity name="System.Text.Encodings.Web" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
Resolved in commit 17d3c36193e49ad88625374734fb57de9f937668

2021-05-05 19:14 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Microsoft/OpenBots.Commands.Microsoft.csproj
> -    <COMReference Include="Microsoft.Office.Core">
Addressed in commit 17d3c36193e49ad88625374734fb57de9f937668

2021-05-05 19:14 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Server/OpenBots.Commands.Asset/CalculateNumberAssetCommand.cs
> +            if (v_AssetActionValue == null)
Resolved in commit 17d3c36193e49ad88625374734fb57de9f937668

2021-05-05 19:14 UTC, openbots-nc commented on OpenBots.Core/Server/API Methods/AssetMethods.cs
> +                var assetSDK = JsonConvert.DeserializeObject<OpenBots.Server.SDK.Model.Asset>(assetString);
Resolved in commit 17d3c36193e49ad88625374734fb57de9f937668

2021-05-05 19:15 UTC, openbots-nc commented on OpenBots.Core/Server/API Methods/CredentialMethods.cs
> +                var credentialSDK = JsonConvert.DeserializeObject<OpenBots.Server.SDK.Model.Credential>(credentialJson);
Resolved in commit 17d3c36193e49ad88625374734fb57de9f937668

2021-05-06 01:08 UTC, openbots-ff commented on OpenBots.Core/Server/Models/Asset.cs
> +        public Guid? FileId { get; set; }
Did you clean out the packages and reinstall them? MethodNotFound exceptions are related to that

2021-05-06 01:09 UTC, openbots-ff commented on OpenBots.Core/Server/User/EnvironmentSettings.cs
> +        public static string serverURL = settings["OpenBotsServerUrl"];
exactly. If you attempt to use server commands without first connecting the agent, this would throw an exception

2021-05-13 14:58 UTC, openbots-ff submitted a review, later dismissed

2021-05-14 20:34 UTC, openbots-ch submitted a review, later dismissed

2021-05-14 20:43 UTC, openbots-ff requested changes

2021-05-14 20:43 UTC, openbots-ff commented on OpenBots.Core/Server/User/EnvironmentSettings.cs
> +        //public static string password = "Blue1093.";
you may want to remove these credentials

2021-05-14 21:09 UTC, openbots-ff approved these changes

2021-05-14 21:10 UTC, openbots-ch approved these changes

2021-05-14 21:12 UTC, merged