Native messaging
OpenBotsAI/OpenBots.Studio pull request #241
Opened 2021-05-06 20:02 UTC by openbots-aw

- Added ChromeNativeMessaging Commands
- Added ChromeNativeMessaging Server Project
- Added Chrome Extension
- Added ChromeNativeMessaging Recorder in Selenium Element Action

2021-05-06 23:40 UTC, openbots-ff requested changes

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands.NativeMessagingAutomation/Class1.cs
> +    public class Class1
is this class necessary?

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingClearTextCommand.cs
> +		[SampleUsage("XPath : \"//*[@id=\"features\"]/div[2]/div/h2/div[\" + var1 + \"]/div\"" +
```suggestion
		[SampleUsage("XPath : \"//*[@id='features']/div[2]/div/h2/div[\" + var1 + \"]/div\"" +
```

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingClearTextCommand.cs
> +		[SampleUsage("XPath : \"//*[@id=\"features\"]/div[2]/div/h2/div[\" + var1 + \"]/div\"" +
this change should be made in all commands

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingClearTextCommand.cs
> +			//SeleniumAction_SelectionChangeCommitted(null, null);
please remove this event handler if you don't intend to use it.

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingCloseBrowserCommand.cs
> +		[SampleUsage("\"MyChromeBrowserInstance\"")]
Instance names are not strings so they should not have quotation marks around them

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingCloseBrowserCommand.cs
> +			v_InstanceName = "\"DefaultChromeBrowser\"";
the sample shouldn't have quotation marks either

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingCreateBrowserCommand.cs
> +        [SampleUsage("https://mycompany.com/orders || {vURL}")]
please add quotation marks to the URL and remove the {} from {vURL}. These changes should be made to all samples.

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingCreateBrowserCommand.cs
> +			System.Threading.Thread.Sleep(7000);
Please shorten this

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingElementExistsCommand.cs.cs
> +			return base.GetDisplayValue() + $" [Element Exists for {searchParameterName}" +
This command has an output so you should include that in the display value the same way it's done in other commands with instances and outputs

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingGetAttributeCommand.cs
> +		[SampleUsage("\"Hello World\" || vAttribute")]
could you provide a more relevant sample here?

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Studio/Resources/Extension/OB Extension/ContentListener.js
> +			//sendResponse({targetHTML: clickPoints});
should this be removed?

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.NativeServer/Properties/AssemblyInfo.cs
> +[assembly: AssemblyTitle("OpenBots.NativeServer")]
please modify all the metadata in this file to match the other projects

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingLeftClickCommand.cs
> +		public NativeMessagingLeftClickCommand()
Could you please combine the click commands?

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingLeftClickCommand.cs
> +		[DisplayName("Browser Instance Name")]
```suggestion
		[DisplayName("Chrome Browser Instance Name")]
```

2021-05-06 23:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingLeftClickCommand.cs
> +		[DisplayName("Browser Instance Name")]
please make this change in all commands to distinguish between these instances and the selenium ones

2021-05-07 11:44 UTC, openbots-aw commented on OpenBots.Commands.NativeMessagingAutomation/Class1.cs
> +    public class Class1
Its removed.

2021-05-07 11:45 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingClearTextCommand.cs
> +			//SeleniumAction_SelectionChangeCommitted(null, null);
Done.

2021-05-07 11:45 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingCloseBrowserCommand.cs
> +		[SampleUsage("\"MyChromeBrowserInstance\"")]
Done.

2021-05-07 11:45 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingCloseBrowserCommand.cs
> +			v_InstanceName = "\"DefaultChromeBrowser\"";
Done.

2021-05-07 11:45 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingCreateBrowserCommand.cs
> +        [SampleUsage("https://mycompany.com/orders || {vURL}")]
Done.

2021-05-07 11:47 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingCreateBrowserCommand.cs
> +			System.Threading.Thread.Sleep(7000);
Changed to 3 seconds.

2021-05-07 11:47 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingElementExistsCommand.cs.cs
> +			return base.GetDisplayValue() + $" [Element Exists for {searchParameterName}" +
Done.

2021-05-07 11:47 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingGetAttributeCommand.cs
> +		[SampleUsage("\"Hello World\" || vAttribute")]
Done.

2021-05-07 12:26 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingLeftClickCommand.cs
> +		public NativeMessagingLeftClickCommand()
Currently only left click is working, and I have tried to make the other clicks work but JavaScript is not supporting. I will have to find the alternate ways to support other clicks. Until then we cannot combine them.

2021-05-07 12:27 UTC, openbots-aw commented on OpenBots.NativeServer/Properties/AssemblyInfo.cs
> +[assembly: AssemblyTitle("OpenBots.NativeServer")]
Updated.

2021-05-07 12:28 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingLeftClickCommand.cs
> +		[DisplayName("Browser Instance Name")]
Updated.

2021-05-07 13:45 UTC, openbots-aw commented on OpenBots.Studio/Resources/Extension/OB Extension/ContentListener.js
> +			//sendResponse({targetHTML: clickPoints});
I have removed the comment.

2021-05-10 15:14 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.UIAutomation/OpenBots.Commands.NativeMessaging/NativeMessagingCreateBrowserCommand.cs
> +			System.Threading.Thread.Sleep(7000);
I didn't mean the time lol. I meant the namespace before it

2021-05-10 17:53 UTC, openbots-ff approved these changes

2021-05-10 20:16 UTC, openbots-ch submitted a review, later dismissed

2021-05-11 13:59 UTC, openbots-ch approved these changes

2021-05-11 14:01 UTC, merged