Publish Project
OpenBotsAI/OpenBots.Studio pull request #26
Opened 2020-09-30 14:04 UTC by openbots-ff

Projects can now be published as nuget packages.
Additionally, All gradient ThemedForms have been swapped with UIForms for a cleaner look

2020-09-30 20:38 UTC, openbots-ch approved these changes

2020-09-30 21:01 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/frmScriptEngine.cs
> +                    //BackColor = Color.OrangeRed;
Please remove this comment.

2020-09-30 21:01 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/frmScriptEngine.cs
> +                    //BackColor = Color.Green;
Remove this as well.

2020-09-30 21:03 UTC, openbots-ab requested changes
Please remove a couple of comments.

2020-09-30 21:33 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/frmScriptEngine.cs
> +                    //BackColor = Color.OrangeRed;
done

2020-09-30 21:33 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/frmScriptEngine.cs
> +                    //BackColor = Color.Green;
done

2020-09-30 21:35 UTC, openbots-ab approved these changes

2020-10-01 12:59 UTC, openbots-ch approved these changes

2020-10-01 13:05 UTC, merged