Studio/Agent/Server Integration
OpenBotsAI/OpenBots.Studio pull request #29
Opened 2020-10-09 06:11 UTC by openbots-ff

- Added commands for Assets, Credentials and QueueItems.
- Server Credentials/Agent Id are accessed via a Registry Key/Environment Variable respectively
- Publishing a project will create a Process in the Server

2020-10-12 17:42 UTC, openbots-ch requested changes

2020-10-12 17:42 UTC, openbots-ch commented on OpenBots.Core/Server/API Methods/ProcessMethods.cs
> +            request.AddParameter("OrganizationId", "ef8a6670-f522-4fcd-a55e-90aa92d1deb7"); //TODO Remove once API is updated to not require it
Lets prioritize this removal before merging.

2020-10-12 17:42 UTC, openbots-ch commented on OpenBots.Core/Server/Interfaces/INamedEntity.cs
> +
Lets leave a note to describe the intent for the file (What purpose it serves). In this case its just an extension point for IEntity, correct?

2020-10-12 17:42 UTC, openbots-ch commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmPublishProject.cs
> +                    NotificationMessage = $"'{_projectName}' was published locally but was unable to connect to the server";
Lets reword this to not assume a connection is attended. Ex: "{_projectName}' was published locally. To publish to an OpenBots Server please install and connect the OpenBots Agent."

2020-10-14 17:18 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.QueueItem/AddQueueItemCommand.cs
> +            QueueItemMethods.EnqueQueueItem(client, queueItem);
Done

2020-10-14 17:23 UTC, openbots-ff commented on OpenBots.Core/Server/API Methods/AuthMethods.cs
> +            var client = new RestClient("https://openbotsserver-dev.azurewebsites.net/");
replaced with URL in settings file

2020-10-14 17:39 UTC, openbots-ff commented on OpenBots.Core/Server/API Methods/ProcessMethods.cs
> +            request.AddParameter("OrganizationId", "ef8a6670-f522-4fcd-a55e-90aa92d1deb7"); //TODO Remove once API is updated to not require it
Nicole's changes are sitting in a PR

2020-10-14 17:42 UTC, openbots-ff commented on OpenBots.Core/Server/Interfaces/INamedEntity.cs
> +
These are just the original server viewmodels that I'm using to deserialize the API responses. I don't think it serves any purpose aside from being a bridge to the other interfaces.

2020-10-14 17:44 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmPublishProject.cs
> +                    NotificationMessage = $"'{_projectName}' was published locally but was unable to connect to the server";
done

2020-10-14 18:11 UTC, openbots-ch submitted a review, later dismissed

2020-10-14 20:01 UTC, openbots-ab approved these changes

2020-10-14 20:34 UTC, openbots-ch approved these changes

2020-10-14 20:34 UTC, merged