Feedback Changes 10/12
OpenBotsAI/OpenBots.Studio pull request #30
Opened 2020-10-16 16:16 UTC by openbots-ff

2020-10-19 14:56 UTC, openbots-ch requested changes

2020-10-19 14:56 UTC, openbots-ch commented on OpenBots.Commands/OpenBots.Commands.Outlook/GetOutlookEmailsCommand.cs
> +        [Remarks("Source folder cannot be a sub mail folder.")]
Lets reword this to "cannot be a subfolder." if that's the intent.

2020-10-19 15:02 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.DataTable/FilterDataTableCommand.cs
>              }
I don't this this is reused anywhere at the moment. I'll put it in core if it ever is, but I might replace this method altogether soon when I redesign the way filtering works (using a datagridview)

2020-10-19 15:08 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Outlook/GetOutlookEmailsCommand.cs
> +        [Remarks("Source folder cannot be a sub mail folder.")]
done

2020-10-19 15:08 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Outlook/MoveCopyOutlookEmailCommand.cs
> +        [Remarks("Destination folder cannot be a sub mail folder.")]
done

2020-10-19 20:30 UTC, openbots-ch submitted a review, later dismissed

2020-10-20 11:25 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Excel/ExcelAppendSheetCommand.cs
> +    [Description("This command activates a specific Worksheet in an Excel Workbook.")]
Please update the description.

2020-10-20 11:25 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Excel/ExcelDeleteRangeCommand.cs
> +        [InputSpecification("'Yes' removes the entire row. 'No' only clears the row of its cell values.")]
```suggestion
        [InputSpecification("'Yes' removes the entire range. 'No' only clears the range of its cell values.")]
```

2020-10-20 11:26 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.List/RemoveListItemCommand.cs
> +    [Description("This command updates an item in an existing List variable at a specified index.")]
Please update the description

2020-10-20 11:26 UTC, openbots-ab commented on OpenBots.Engine/AutomationEngineInstance.cs
> +                    //command.IsExceptionIgnored = true;
Please remove this comment.

2020-10-20 11:27 UTC, openbots-ab commented on OpenBots.Engine/AutomationEngineInstance.cs
> +                    //command.IsExceptionIgnored = true;
Please remove this comment.

2020-10-20 11:28 UTC, openbots-ab requested changes
Please make a few requested changes

2020-10-20 13:42 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Excel/ExcelAppendSheetCommand.cs
> +    [Description("This command activates a specific Worksheet in an Excel Workbook.")]
done

2020-10-20 13:43 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Excel/ExcelDeleteRangeCommand.cs
> +        [InputSpecification("'Yes' removes the entire row. 'No' only clears the row of its cell values.")]
done

2020-10-20 13:44 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Excel/ExcelRenameSheetCommand.cs
> +    [Description("This command activates a specific Worksheet in an Excel Workbook.")]
done

2020-10-20 13:44 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.List/RemoveListItemCommand.cs
> +    [Description("This command updates an item in an existing List variable at a specified index.")]
done

2020-10-20 13:46 UTC, openbots-ff commented on OpenBots.Engine/AutomationEngineInstance.cs
> +                    //command.IsExceptionIgnored = true;
I'm keeping it for now because it solved a bug but I can't remember why it was needed in the first place.

2020-10-20 13:46 UTC, openbots-ff commented on OpenBots.Engine/AutomationEngineInstance.cs
> +                    //command.IsExceptionIgnored = true;
same as above

2020-10-20 13:53 UTC, openbots-ch submitted a review, later dismissed

2020-10-20 14:00 UTC, openbots-ab approved these changes

2020-10-20 14:02 UTC, openbots-ch approved these changes

2020-10-20 14:03 UTC, merged