Add unit test projects for the ReadTextFile and MergeDataTable commands.
OpenBotsAI/OpenBots.Studio pull request #42
Opened 2020-11-10 18:16 UTC by openbots-su

This merge request includes a minor bugfix for OpenBots.Core/Common/Common.cs.

2020-11-10 21:06 UTC, openbots-ff requested changes

2020-11-10 21:27 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/MergeDataTableCommandTests.cs
> +        public void HandlesNullDataTables(System.Data.DataTable dt1, System.Data.DataTable dt2)
Addressed in https://github.com/OpenBotsAI/OpenBots.Studio/pull/42/commits/6d8a1453d5f97b675f56cc51cf130d3218dac4b0

2020-11-10 21:27 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.TextFile.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.0.0.0")]
Addressed in https://github.com/OpenBotsAI/OpenBots.Studio/pull/42/commits/6d8a1453d5f97b675f56cc51cf130d3218dac4b0

2020-11-10 21:27 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.TextFile.Test/ReadTextFileCommandTests.cs
> +        public void handlesNonexistentFile()
Addressed in https://github.com/OpenBotsAI/OpenBots.Studio/pull/42/commits/6d8a1453d5f97b675f56cc51cf130d3218dac4b0

2020-11-10 21:27 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.TextFile.Test/ReadTextFileCommandTests.cs
> +            var textFromFile = File.ReadAllText(_readTextFile.v_FilePath);
Addressed in https://github.com/OpenBotsAI/OpenBots.Studio/pull/42/commits/6d8a1453d5f97b675f56cc51cf130d3218dac4b0

2020-11-11 18:58 UTC, openbots-ch submitted a review, later dismissed

2020-11-17 20:28 UTC, openbots-ch approved these changes

2020-11-17 21:16 UTC, openbots-ff requested changes

2020-11-17 21:16 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/CreateDataTableCommandTests.cs
> +            //columnNameDataTable.StoreInUserVariable(_engine, "{columnNames}");
leftover comment

2020-11-17 21:16 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/CreateDataTableCommandTests.cs
> +            columnNameDataTable.Columns.Add("Col1");
Remember that one of the main purpose of these tests is to make sure the commands are retrieving the variables correctly from the engine. Rather than using "Col1", you should use a variable, i.e. "{col}" with a value of "Col1". Avoid hardcoded values whenever possible.

2020-11-17 21:16 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/FilterDataTableCommandTests.cs
> +            _filterDataTable.v_SearchItem = "(col1,id1)";
same as previous comment. Try something like "({col},{ed})" here and in lines 36 and 37.

2020-11-17 21:16 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/FilterDataTableCommandTests.cs
> +using System.Threading.Tasks;
ctrl + R + G to clean and sort all your usings in all files

2020-11-17 21:16 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/CreateDataTableCommandTests.cs
> +
This is just a minor thing, but please mind the extra spacing here. Try to make the formatting consistent with all the other tests.

2020-11-18 15:56 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/AddDataRowCommandTests.cs
> +            //output.WriteLine(_addDataRow.v_DataRowDataTable.Columns[0].ToString());
Addressed in bb6ca22ea2d19ba11ee8c72461bf32fb36f9a8e2

2020-11-18 15:56 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/CreateDataTableCommandTests.cs
> +            //columnNameDataTable.StoreInUserVariable(_engine, "{columnNames}");
Addressed in bb6ca22ea2d19ba11ee8c72461bf32fb36f9a8e2

2020-11-18 15:56 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/CreateDataTableCommandTests.cs
> +            columnNameDataTable.Columns.Add("Col1");
Addressed in bb6ca22ea2d19ba11ee8c72461bf32fb36f9a8e2

2020-11-18 15:56 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/FilterDataTableCommandTests.cs
> +            _filterDataTable.v_SearchItem = "(col1,id1)";
Addressed in bb6ca22ea2d19ba11ee8c72461bf32fb36f9a8e2

2020-11-18 15:56 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/FilterDataTableCommandTests.cs
> +using System.Threading.Tasks;
Addressed in bb6ca22ea2d19ba11ee8c72461bf32fb36f9a8e2

2020-11-18 15:57 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/CreateDataTableCommandTests.cs
> +
Addressed in bb6ca22ea2d19ba11ee8c72461bf32fb36f9a8e2

2020-11-21 04:40 UTC, openbots-ff requested changes
Just one little cleanup and it'll be ready to merge. Great job!

2020-11-21 04:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/RemoveDataRowCommandTests.cs
> +            //output.WriteLine(outputTable.Rows[0][0].ToString());
please delete comment

2020-11-23 14:15 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.DataTable.Test/RemoveDataRowCommandTests.cs
> +            //output.WriteLine(outputTable.Rows[0][0].ToString());
Addressed in f9c1616d494f6268c6d442b04765a6eb3ff835aa

2020-11-23 15:00 UTC, openbots-ff approved these changes

2020-11-23 15:09 UTC, openbots-ch approved these changes

2020-11-23 15:20 UTC, merged