Added tests for the dictionary command suite
OpenBotsAI/OpenBots.Studio pull request #44
Opened 2020-11-17 14:05 UTC by openbots-su

2020-11-20 14:19 UTC, openbots-ch approved these changes

2020-11-21 04:48 UTC, openbots-ff requested changes

2020-11-21 04:48 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Dictionary.Test/CreateDictionaryCommandTests.cs
> +            _createDictionary.v_ColumnNameDataTable = (Data.DataTable)"{inputDt}".ConvertUserVariableToObject(_engine);
Do you still need this alias here? You should just be able to use (DataTable) since there are no overlapping namespaces.

2020-11-23 14:23 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Dictionary.Test/CreateDictionaryCommandTests.cs
> +            _createDictionary.v_ColumnNameDataTable = (Data.DataTable)"{inputDt}".ConvertUserVariableToObject(_engine);
Addressed in e6a09fc84753e7643eaa4d8995fbb4bed1baef56

2020-11-23 15:01 UTC, openbots-ff approved these changes

2020-11-23 15:03 UTC, openbots-ch approved these changes

2020-11-23 15:03 UTC, merged