Data command tests
OpenBotsAI/OpenBots.Studio pull request #46
Opened 2020-11-24 13:06 UTC by openbots-su

2020-11-25 20:32 UTC, openbots-ff requested changes

2020-11-25 20:32 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Data.Test/CreateDateTimeCommandTests.cs
> +            string year = "2020";
remember to use engine variables wherever possible. At least once per command. That way if we make changes to the variable conversion method, the command will fail at least once.

2020-11-25 20:32 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Data.Test/MathCalculationCommandTests.cs
> +            string thouSeparator = ",";
try the alternative versions. For example, a period for thousands and comma for decimal. Since that's the reason this option exists.

2020-11-25 20:32 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Data.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2020")]
I forgot to point this out previously but I think the copyright (and potentially other assembly metadata) don't match the commands. Should be something with "OpenBots"

2020-11-25 20:32 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Data.Test/SplitTextCommandTests.cs
> +            string splitCharacter = " ";
I believe split text now supports splitting with multiple delimiters. The input should be a list of string characters. Please test.

2020-11-25 20:32 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Data/GetPDFTextCommand.cs
> +			ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
should this be limited to just TLS?

2020-11-25 20:59 UTC, openbots-ch requested changes

2020-11-25 20:59 UTC, openbots-ch commented on OpenBots.Commands/OpenBots.Commands.Data.Test/GetPDFTextCommandTests.cs
> +    }
Let's throw an additional test in for invalid/incorrect path given. Gives us a sanity check to contract the positive case if one begins failing.

2020-11-27 15:21 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Data.Test/CreateDateTimeCommandTests.cs
> +            string year = "2020";
Addressed in d03ac7b5287cd4b9ac0d013b2bac0008e0012055

2020-11-27 15:21 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Data.Test/MathCalculationCommandTests.cs
> +            string thouSeparator = ",";
Addressed in d03ac7b5287cd4b9ac0d013b2bac0008e0012055

2020-11-27 15:22 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Data.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2020")]
Addressed for TextFile, Dictionary, and Data command test suites in d03ac7b5287cd4b9ac0d013b2bac0008e0012055

2020-11-27 15:22 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Data.Test/SplitTextCommandTests.cs
> +            string splitCharacter = " ";
Addressed in d03ac7b5287cd4b9ac0d013b2bac0008e0012055

2020-11-27 15:25 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Data/GetPDFTextCommand.cs
> +			ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
I will need to do more research to come up with a list of networking protocols we may want to include and why each one would be necessary. This could be something good to discuss further so we have a standard set we will support in the future. For now, I will be matching the supported protocols to those supported by the Nuget Package Manager which also utilizes the ServicePointManager.
Addressed in d03ac7b5287cd4b9ac0d013b2bac0008e0012055

2020-11-27 15:25 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Data.Test/GetPDFTextCommandTests.cs
> +    }
Addressed in d03ac7b5287cd4b9ac0d013b2bac0008e0012055

2020-11-29 02:34 UTC, openbots-ff requested changes

2020-11-29 02:34 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Data.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCompany("Accelirate Inc.")]
There should be no mention of Accelirate anywhere in the solution. I believe Cameron had already replaced it with OpenBots in the command assemblyinfo files, assuming that's where you copied this metadata from?

2020-11-30 18:52 UTC, openbots-ch approved these changes

2020-11-30 19:35 UTC, openbots-ff approved these changes

2020-11-30 19:35 UTC, merged