Splitted Up Studio Commands
OpenBotsAI/OpenBots.Studio pull request #47
Opened 2020-11-25 18:49 UTC by openbots-ab

- Moved out all the Studio Commands to separate projects (placed under **OpenBots.Commands** solution folder)
- Resolved all the Commands references in Studio (Instantiating the Commands at runtime from the loaded assemblies)

2020-11-25 20:16 UTC, openbots-ff requested changes

2020-11-25 20:16 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmAdvancedUIElementRecorder.cs
> +                //var setTextElementActionCommand = new UIAutomationCommand
comment

2020-11-25 20:16 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmAdvancedUIElementRecorder.cs
> +            //var commentCommand = new AddCodeCommentCommand
comment

2020-11-25 20:16 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmAdvancedUIElementRecorder.cs
> +            //var sequenceCommand = new SequenceCommand
comment

2020-11-25 20:16 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmUIRecorder.cs
> +                //var newSequence = new SequenceCommand();
comment

2020-11-25 20:16 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmUIRecorder.cs
> +                //var newSequence = new SequenceCommand();
comment

2020-11-25 20:16 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmUIRecorder.cs
> +                            //newSequence = new SequenceCommand();
comment

2020-11-25 20:16 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmUIRecorder.cs
> +                        //newSequence = new SequenceCommand();
comment

2020-11-25 20:16 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmUIRecorder.cs
> +            //var commentCommand = new AddCodeCommentCommand
comment

2020-11-25 20:16 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmWebElementRecorder.cs
> +                        //_createBrowserCommand = new SeleniumCreateBrowserCommand
please clean up all comments in this file

2020-11-25 20:16 UTC, openbots-ff commented on OpenBots.Studio/UI/Forms/frmCommandEditor.cs
> +//using OpenBots.Commands;
comment

2020-11-25 20:16 UTC, openbots-ff commented on OpenBots.Studio/Utilities/GlobalHook.cs
> +                //var keyboardCommand = new SendKeystrokesCommand
please clean comments

2020-11-25 20:16 UTC, openbots-ff commented on OpenBots.UI/SupplementForms/frmImageCapture.cs
> +namespace OpenBots.UI.SupplementForms
Why was this namespace changed/form moved? I don't think it matches with the other supplement forms

2020-11-26 14:28 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.ErrorHandling/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.0.0.0")]
Changed the versions to 1.1.0.0 but I am not well aware of the other metadata you're pointing to.
Need clarification on that.

2020-11-26 14:29 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.If/BeginIfCommand.cs
> +			///
Removed the comment

2020-11-26 14:29 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Input/UIAutomationCommand.cs
> +namespace OpenBots.Commands.Misc
done

2020-11-26 14:29 UTC, openbots-ab commented on OpenBots.Commands/OpenBots.Commands.Input/UIAutomationCommand.cs
> -		public PropertyCondition CreatePropertyCondition(string propertyName, object propertyValue)
It was moved to **OpenBots.Core/Utilities/CommandUtilities/CommandsHelper.cs** along with the other method **SearchForGUIElement** as it's being used by this method only.

2020-11-26 14:29 UTC, openbots-ab commented on OpenBots.Core/Utilities/FormsUtilities/FormsHelper.cs
> +            foreach (Form form in Application.OpenForms)
Yes, forms are hiding/showing properly. I tested it.

2020-11-26 14:29 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/ScriptBuilder Forms/frmScriptBuilder.cs
> +            //var mouseMove = new SendMouseMoveCommand
removed this piece of code as it is only creating an instance of **SendMouseMoveCommand**

2020-11-26 14:30 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/ScriptBuilder Forms/frmScriptBuilderProject.cs
> +                //ShowMessageCommand helloWorldCommand = new ShowMessageCommand();
removed the comment

2020-11-26 14:30 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmAdvancedUIElementRecorder.cs
> +                    //ActivateWindowCommand activateWindowCommand = new ActivateWindowCommand
removed

2020-11-26 14:30 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmAdvancedUIElementRecorder.cs
> +            //var clickElementActionCommand = new UIAutomationCommand
removed

2020-11-26 14:30 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmAdvancedUIElementRecorder.cs
> +            //var waitElementActionCommand = new UIAutomationCommand
removed

2020-11-26 14:31 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmAdvancedUIElementRecorder.cs
> +                //var setTextElementActionCommand = new UIAutomationCommand
removed

2020-11-26 14:32 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmAdvancedUIElementRecorder.cs
> +            //var commentCommand = new AddCodeCommentCommand
removed

2020-11-26 14:32 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmAdvancedUIElementRecorder.cs
> +            //var sequenceCommand = new SequenceCommand
removed

2020-11-26 14:32 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmUIRecorder.cs
> +                //var newSequence = new SequenceCommand();
removed

2020-11-26 14:32 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmUIRecorder.cs
> +                //var newSequence = new SequenceCommand();
removed

2020-11-26 14:32 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmUIRecorder.cs
> +                            //newSequence = new SequenceCommand();
removed

2020-11-26 14:32 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmUIRecorder.cs
> +                        //newSequence = new SequenceCommand();
removed

2020-11-26 14:32 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmUIRecorder.cs
> +            //var commentCommand = new AddCodeCommentCommand
removed

2020-11-26 14:32 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/Supplement Forms/frmWebElementRecorder.cs
> +                        //_createBrowserCommand = new SeleniumCreateBrowserCommand
removed

2020-11-26 14:33 UTC, openbots-ab commented on OpenBots.Studio/UI/Forms/frmCommandEditor.cs
> +//using OpenBots.Commands;
removed

2020-11-26 14:33 UTC, openbots-ab commented on OpenBots.Studio/Utilities/GlobalHook.cs
> +                //var keyboardCommand = new SendKeystrokesCommand
removed

2020-11-26 14:33 UTC, openbots-ab commented on OpenBots.UI/SupplementForms/frmImageCapture.cs
> +namespace OpenBots.UI.SupplementForms
This form was moved to OpenBots.UI (new project)

2020-11-29 02:56 UTC, openbots-ff requested changes

2020-11-29 02:56 UTC, openbots-ff commented on OpenBots.Studio/Utilities/TypeMethods.cs
> +        {
My one concern with the way this is handling command types is that it assumes that the requested "typeName" already exists in the appDomain. What happens when you've removed all the command dlls from the solution and run the studio without any commands at all?

2020-11-30 11:02 UTC, openbots-ab commented on OpenBots.Studio/Utilities/TypeMethods.cs
> +        {
In this case, a dialog box with the specific message will be shown to the user so that user would be able to download/load required dependency from Package Manager and then retry. For reference, please see the method **CreateTypeInstance** at line 21 in this file.

2020-11-30 11:38 UTC, openbots-ab commented on OpenBots.Studio/Utilities/TypeMethods.cs
> +        {
I have just moved the code (for displaying dialog box with proper message) to **GetTypeByName**.

2020-12-01 14:43 UTC, openbots-ff approved these changes

2020-12-01 15:03 UTC, openbots-ff approved these changes

2020-12-01 15:46 UTC, openbots-ch approved these changes

2020-12-01 15:46 UTC, merged