List command tests
OpenBotsAI/OpenBots.Studio pull request #48
Opened 2020-11-27 14:24 UTC by openbots-su

2020-11-29 02:48 UTC, openbots-ff requested changes

2020-11-29 02:48 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.List.Tests/AddListItemCommandTests.cs
> +            Generic.List<string> stringList = new List<string>();
Is this "Generic" alias needed? Given that you seem to be able to initialize a "new List<string>()" without it.

2020-11-29 02:48 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.List.Tests/CreateListCommandTests.cs
> +            // However, there is currently an issue where 2 List<MailItem> values return false despite being the same type.
try going to the outlook reference properties and set "embed interop types" to false

2020-11-29 02:48 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.List.Tests/RemoveListItemCommandTests.cs
> +        public void RemovesListItem()
I would include a test for a list of one of the complex types, maybe DataTable since it's the easiest, in each test. Mainly because it uses a different variable conversion method from the string types. Back when I made a lot of changes to the variable conversion methods, the list commands broke the most.

2020-11-29 02:49 UTC, openbots-ff requested changes

2020-11-29 02:49 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.List.Tests/AddListItemCommandTests.cs
> +        public void AddsDataTableListItem()
I think this needs a "HandlesInvalidListItem" test as well

2020-11-30 16:18 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.List.Tests/AddListItemCommandTests.cs
> +            Generic.List<string> stringList = new List<string>();
Resolved in 14bd42794c0b8f8fac851bb52d7b36fbfe63a2b6

2020-11-30 16:19 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.List.Tests/CreateListCommandTests.cs
> +            // However, there is currently an issue where 2 List<MailItem> values return false despite being the same type.
Addressed in 3e98901118de7fd6d0e822a974fcdff28ae798e0

2020-11-30 16:27 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.List.Tests/RemoveListItemCommandTests.cs
> +        public void RemovesListItem()
Addressed in 4b83f730710b1ab7aed4a9505774888bb3578c3a

2020-11-30 16:27 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.List.Tests/AddListItemCommandTests.cs
> +        public void AddsDataTableListItem()
Addressed in f9ebaed5c26e73c25546d44e445e5056bce35197

2020-11-30 19:34 UTC, openbots-ff approved these changes

2020-11-30 19:39 UTC, openbots-ch approved these changes

2020-11-30 19:39 UTC, merged