Tests created for credential commands
OpenBotsAI/OpenBots.Studio pull request #49
Opened 2020-12-01 14:19 UTC by openbots-su

2020-12-01 14:53 UTC, openbots-ff requested changes

2020-12-01 14:53 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Credential.Tests/GetCredentialCommandTests.cs
> +            credentialName.StoreInUserVariable(_engine, "{credName}");
So this test is dependent on the credential actually existing in the server. So if the db is wiped or the server url changes, it won't work anymore. I wonder if there anything we can do to mock that? @CameronHerwig any thoughts?

2020-12-01 14:53 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Credential/GetCredentialCommand.cs
> +			CommandEnabled = true;
I'd rather you didn't add this to the commands directly. It's already working in studio so I don't think we be reusing code like this in all the http based commands.

2020-12-01 14:54 UTC, openbots-ff requested changes

2020-12-01 14:54 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Credential/GetCredentialCommand.cs
> +			ServicePointManager.SecurityProtocol |= (SecurityProtocolType.Ssl3 |
I'd rather you didn't add this to the commands directly. It's already working in studio so I don't think we be reusing code like this in all the http based commands.

2020-12-01 16:49 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Credential/GetCredentialCommand.cs
> +			ServicePointManager.SecurityProtocol |= (SecurityProtocolType.Ssl3 |
Addressed in e2483ee14ec2b5b98e28cbea37e8e63e4effe7e4
Security Protocol setup code moved to a common method in OpenBots core.

2020-12-01 18:23 UTC, openbots-ch commented on OpenBots.Commands/OpenBots.Commands.Credential.Tests/GetCredentialCommandTests.cs
> +            credentialName.StoreInUserVariable(_engine, "{credName}");
I would say we can rely on the dependent entities existing on the Dev server. If the test fail we can do a simple sanity check on the Server. It comes with the territory for these commands.

2020-12-01 18:40 UTC, openbots-ch approved these changes

2020-12-01 20:24 UTC, openbots-ff approved these changes

2020-12-01 20:30 UTC, openbots-ff approved these changes

2020-12-03 14:43 UTC, openbots-ch approved these changes

2020-12-03 14:43 UTC, merged