Package Manager
OpenBotsAI/OpenBots.Studio pull request #52
Opened 2020-12-03 23:50 UTC by openbots-ff

TODO: Write description. For review only. Do not merge yet.

2020-12-08 17:32 UTC, openbots-su submitted a review, later dismissed

2020-12-08 19:42 UTC, openbots-ch requested changes

2020-12-08 23:05 UTC, openbots-ch commented on OpenBots.Core/Nuget/AppDomainSetupManager.cs
> +                    var assemblies = AppDomain.CurrentDomain.GetAssemblies();
Resolved in [https://github.com/OpenBotsAI/OpenBots.Studio/pull/52/commits/f9897c4419e03241cc85da5c8ab98a82a4cb59d2](f9897c4)

2020-12-08 23:06 UTC, openbots-ch approved these changes

2020-12-08 23:07 UTC, openbots-ch commented
Additional optimization for NuGet loading to follow in separate PR.

2020-12-09 14:58 UTC, openbots-su approved these changes

2020-12-09 15:01 UTC, merged