Asset command tests
OpenBotsAI/OpenBots.Studio pull request #53
Opened 2020-12-04 16:33 UTC by openbots-su

2020-12-04 20:58 UTC, openbots-ff requested changes

2020-12-04 20:58 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Asset.Tests/GetAssetCommandTests.cs
> +            Assert.Throws<Exception>(() => _getAsset.RunCommand(_engine));
Is there a way to assert that the exception is an asset not found exception rather than a failed connection exception?

2020-12-04 20:58 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Asset.Tests/UpdateAssetCommandTests.cs
> +
would you please clean up some of these double spaces?

2020-12-04 21:17 UTC, openbots-ch requested changes

2020-12-04 21:17 UTC, openbots-ch commented on OpenBots.Commands/OpenBots.Commands.Asset.Tests/UpdateAssetCommandTests.cs
> +            Assert.Throws<Exception>(() => _updateAsset.RunCommand(_engine));
Let's go ahead and update the underlying command exception type to be more specific, and have the test reflect it.

2020-12-04 21:26 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Asset.Tests/UpdateAssetCommandTests.cs
> +            Assert.Throws<Exception>(() => _updateAsset.RunCommand(_engine));
Would we prefer a customer exception from the OpenBots namespace, or something more generic already found in .NET such as ObjectNotFoundException?
https://docs.microsoft.com/en-us/dotnet/api/system.data.objectnotfoundexception?view=netframework-4.8

2020-12-04 21:28 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Asset.Tests/UpdateAssetCommandTests.cs
> +
Addressed in 1fcb8e66a55b3c3051e9c597314f9613547a45fa

2020-12-04 23:46 UTC, openbots-ch commented on OpenBots.Commands/OpenBots.Commands.Asset.Tests/UpdateAssetCommandTests.cs
> +            Assert.Throws<Exception>(() => _updateAsset.RunCommand(_engine));
We can stick to .NET exception for now, and evaluate custom exceptions at a later point.

2020-12-07 14:45 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Asset.Tests/UpdateAssetCommandTests.cs
> +            Assert.Throws<Exception>(() => _updateAsset.RunCommand(_engine));
Addressed in c02b1fceb4fca0937222ec2bdf409e37079c2739

2020-12-07 14:47 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Asset.Tests/GetAssetCommandTests.cs
> +            Assert.Throws<Exception>(() => _getAsset.RunCommand(_engine));
Addressed in c02b1fceb4fca0937222ec2bdf409e37079c2739

2020-12-07 16:26 UTC, openbots-ff approved these changes

2020-12-07 16:31 UTC, openbots-ch approved these changes

2020-12-07 16:31 UTC, merged