Add CalculateNumberAssetCommand to OpenBots.Commands.Asset
OpenBotsAI/OpenBots.Studio pull request #55
Opened 2020-12-08 22:00 UTC by ncarrero

- Create CalculateNumberAssetCommand.cs in OpenBots.Commands.Asset project
- Add necessary methods in AssetMethods and image in UIImage

2020-12-08 23:14 UTC, openbots-ff requested changes
Looks good. Please add tests for this command as well

2020-12-08 23:14 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Asset/CalculateNumberAssetCommand.cs
> +        [Remarks("This command will throw an exception if an asset of the wrong type is used")]
```suggestion
        [Remarks("This command will throw an exception if an asset of the wrong type is used.")]
```

2020-12-08 23:14 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Asset/CalculateNumberAssetCommand.cs
> +                return base.GetDisplayValue() + $" (Increment) ['{v_AssetName}']";
```suggestion
                return base.GetDisplayValue() + $" [Increment '{v_AssetName}']";
```

2020-12-08 23:14 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Asset/CalculateNumberAssetCommand.cs
> +                return base.GetDisplayValue() + $" (Increment) ['{v_AssetName}']";
square brackets should surround the entire display message. Please use other commands as a reference.

2020-12-09 15:10 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Asset/CalculateNumberAssetCommand.cs
> +                throw new Exception($"No Asset was found for '{vAssetName}' and type 'Number'");
Change this to an ObjectNotFoundException please.
https://docs.microsoft.com/en-us/dotnet/api/system.data.objectnotfoundexception?view=netframework-4.8

2020-12-09 18:05 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Asset/CalculateNumberAssetCommand.cs
> +                throw new Exception($"No Asset was found for '{vAssetName}' and type 'Number'");
Changed to DataException to stay consistennt with Get Asset and Update Asset Commands

2020-12-09 18:12 UTC, openbots-ff requested changes

2020-12-09 18:12 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Asset/CalculateNumberAssetCommand.cs
>                  return base.GetDisplayValue() + $" (Decrement) ['{v_AssetName}']";
You forgot to update the other ones.

2020-12-09 18:31 UTC, openbots-ff submitted a review, later dismissed

2020-12-09 18:39 UTC, openbots-ff approved these changes

2020-12-09 18:44 UTC, openbots-ff approved these changes

2020-12-09 18:46 UTC, openbots-su approved these changes

2020-12-09 18:48 UTC, merged