Created AppenTextAssetCommand
OpenBotsAI/OpenBots.Studio pull request #56
Opened 2020-12-08 22:47 UTC by DaironHernandez

- Adds AppendTextAssetCommand to the Asset Commands and adds AppendAsset() method to AssetMethods.cs

2020-12-08 23:09 UTC, openbots-ff requested changes
Please add a test for this command, but otherwise, it looks great!

2020-12-08 23:09 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Asset/AppendTextAssetCommand.cs
> +		[Remarks("This command will throw an exception if an asset of the wrong type is used")]
```suggestion
		[Remarks("This command will throw an exception if an asset of the wrong type is used.")]
```

2020-12-09 15:08 UTC, openbots-su requested changes
As mentioned in the other comment, you just need to implement a test for the command. Otherwise, I don't see any issues in the command itself.

2020-12-11 21:31 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Asset/AppendTextAssetCommand.cs
> +		[Remarks("This command will throw an exception if an asset of the wrong type is used")]
Period for remark added in b53b3e67306b416db58cefede369ad61d22da5b0

Tests for this command added in b6b2f68 and 6d31657

2020-12-11 21:31 UTC, openbots-su approved these changes

2020-12-11 21:43 UTC, openbots-ff approved these changes

2020-12-11 21:47 UTC, openbots-ff approved these changes

2020-12-11 21:51 UTC, openbots-ch approved these changes

2020-12-11 21:51 UTC, openbots-su approved these changes

2020-12-11 21:51 UTC, merged