Get email property commands
OpenBotsAI/OpenBots.Studio pull request #57
Opened 2020-12-09 14:59 UTC by openbots-su

2020-12-09 18:38 UTC, openbots-ff requested changes
Please update the UIImage.cs file as well.

2020-12-09 18:38 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Email/GetMimeMessageProperty.cs
> +        [Editor("ShowVariableHelper", typeof(UIAdditionalHelperType))]
Please remove the variable helper from the output

2020-12-09 18:38 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Email/GetMimeMessageProperty.cs
> +            RenderedControls.AddRange(commandControls.CreateDefaultInputGroupFor("v_Property", this, editor));
This should be a dropdowngroup

2020-12-09 18:38 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Email/GetMimeMessageProperty.cs
> +            return base.GetDisplayValue() + $" [From '{v_MimeMessage}' - Get '{v_Property} value' - Store property in '{v_OutputUserVariableName}']";
please use APA title capitalization convention https://capitalizemytitle.com/

2020-12-09 18:38 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Outlook/GetOutlookEmailPropertyCommand.cs
> +}
missing Render and DisplayValue code

2020-12-09 20:34 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Email/GetMimeMessageProperty.cs
> +        [Editor("ShowVariableHelper", typeof(UIAdditionalHelperType))]
Addressed in 0ff24ed9f317606cece239b2c1153d09e916d8f4

2020-12-09 20:34 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Email/GetMimeMessageProperty.cs
> +            RenderedControls.AddRange(commandControls.CreateDefaultInputGroupFor("v_Property", this, editor));
Addressed in 0ff24ed9f317606cece239b2c1153d09e916d8f4

2020-12-09 20:34 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Email/GetMimeMessageProperty.cs
> +            return base.GetDisplayValue() + $" [From '{v_MimeMessage}' - Get '{v_Property} value' - Store property in '{v_OutputUserVariableName}']";
Addressed in 0ff24ed9f317606cece239b2c1153d09e916d8f4

2020-12-09 20:35 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Outlook/GetOutlookEmailPropertyCommand.cs
> +}
Implemented in 17285f3a7a725e856268dc2ba9ef74dccb0b322c

2020-12-09 22:50 UTC, openbots-ff requested changes

2020-12-09 22:50 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Outlook/GetOutlookEmailPropertyCommand.cs
> +            return base.GetDisplayValue() + $" [From '{v_MailItem}' - Get '{v_Property} Value' - Store Property in '{v_OutputUserVariableName}']";
```suggestion
            return base.GetDisplayValue() + $" [From '{v_MailItem}' - Get '{v_Property}' Value - Store Property in '{v_OutputUserVariableName}']";
```

2020-12-09 22:50 UTC, openbots-ff commented on OpenBots.Studio/UI/CustomControls/CustomUIControls/UIImage.cs
> +            uiImages.Add("GetMimeMessagePropertyCommand", Resources.command_queueitem);
please use the appropriate Resource. These aren't queueitem commands

2020-12-09 22:50 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Email/GetMimeMessagePropertyCommand.cs
> +            return base.GetDisplayValue() + $" [From '{v_MimeMessage}' - Get '{v_Property} Value' - Store Property in '{v_OutputUserVariableName}']";
```suggestion
            return base.GetDisplayValue() + $" [From '{v_MimeMessage}' - Get '{v_Property}' Value - Store Property in '{v_OutputUserVariableName}']";
```

2020-12-10 20:32 UTC, openbots-ch requested changes

2020-12-10 20:32 UTC, openbots-ch commented on OpenBots.Commands/OpenBots.Commands.Outlook/GetOutlookEmailPropertyCommand.cs
> +                    break;
See previous comment.

2020-12-11 15:23 UTC, openbots-su commented on OpenBots.Studio/UI/CustomControls/CustomUIControls/UIImage.cs
> +            uiImages.Add("GetMimeMessagePropertyCommand", Resources.command_queueitem);
Corrected in b0d30b8015b87359003a8592213e4e7b45307b95

2020-12-11 15:23 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Email/GetMimeMessagePropertyCommand.cs
> +            return base.GetDisplayValue() + $" [From '{v_MimeMessage}' - Get '{v_Property} Value' - Store Property in '{v_OutputUserVariableName}']";
Addressed in 6a35264215e279a3c4171c42587d26c8b9ba77e3

2020-12-11 15:24 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Email/GetMimeMessagePropertyCommand.cs
> +                    break;
Addressed in 6a35264215e279a3c4171c42587d26c8b9ba77e3

2020-12-11 20:32 UTC, openbots-ch submitted a review, later dismissed

2020-12-11 21:40 UTC, openbots-ff requested changes

2020-12-11 21:40 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Loop/OpenBots.Commands.Loop.csproj
> +    <Reference Include="System">
please undo everything in this file except for the having set outlook interop to false

2020-12-11 21:59 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.Loop/OpenBots.Commands.Loop.csproj
> +    <Reference Include="System">
Addressed in 6055e294a1565547ef8d15716d8039a799d13daf

2020-12-11 22:10 UTC, openbots-ff approved these changes

2020-12-11 22:12 UTC, openbots-ch approved these changes

2020-12-11 22:12 UTC, merged