Contains Commands Added and MatchCalculation Fixed
OpenBotsAI/OpenBots.Studio pull request #61
Opened 2020-12-11 16:58 UTC by openbots-aw

- Added StringContainsCommand
- Fixed MathCalculationCommand if equation returns infinity

2020-12-11 21:42 UTC, openbots-ch requested changes

2020-12-11 22:05 UTC, openbots-ff requested changes

2020-12-11 22:05 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Data/StringContainsCommand.cs
> +            return base.GetDisplayValue() + $" [If ('{v_FullText}') Contains ('{v_ComparisonText}') - " +
```suggestion
            return base.GetDisplayValue() + $" [If '{v_FullText}' Contains '{v_ComparisonText}' - " +
```

2020-12-11 22:05 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Data/StringContainsCommand.cs
> +                $"Store bool in '{v_OutputUserVariableName}']";
```suggestion
                $"Store Bool in '{v_OutputUserVariableName}']";
```

2020-12-11 22:05 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Data/StringContainsCommand.cs
> +    [Description("This command returns a boolean if it contains string.")]
```suggestion
    [Description("This command checks if a string contains a specified substring and returns the result.")]
```

2020-12-11 22:05 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Data/MathCalculationCommand.cs
> +		[Description("Specify if equation could return undefined.")]
```suggestion
		[Description("Specify whether the equation can return undefined as a valid result. Otherwise throw a 'DivideByZeroException'.")]
```

2020-12-14 12:28 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Data/StringContainsCommand.cs
> +    [Description("This command returns a boolean if it contains string.")]
Description is changed to "This command checks if a string contains a specified substring and returns the result." as suggested by Francesca.

2020-12-14 12:54 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Data/MathCalculationCommand.cs
> +			var acceptUndefined = v_AcceptUndefined.ConvertUserVariableToString(engine);
Changed as suggested.

2020-12-14 12:54 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Data/MathCalculationCommand.cs
> +		[Required]
Changed as suggested

2020-12-14 14:22 UTC, openbots-ff requested changes
Please add an entry to UIImage.cs with the appropriate resource for the new command. Also, please add the name of the new command to the Data Command .nuspec tags

2020-12-14 16:43 UTC, openbots-ff approved these changes

2020-12-14 16:50 UTC, openbots-ch approved these changes

2020-12-14 16:50 UTC, merged