Server commands2
OpenBotsAI/OpenBots.Studio pull request #63
Opened 2020-12-12 15:02 UTC by openbots-nc

- Add SendServerEmailCommand to list of Commands
- Refactor QueueItem commands to allow for attachment of files
- Test ServerEmail, QueueItem, Credential, and Asset commands to ensure proper functionality (update Asset will be fixed in the near future)

2020-12-12 15:22 UTC, openbots-ff requested changes

2020-12-12 15:22 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.QueueItem/WorkQueueItemCommand.cs
> +										 .ToDictionary(i => i.Key, i => i.Value);
Do queueitems have a property for the number of attachments? If they do, you might want to add that here. What this is is a filter of just the relevant properties that the user would want to see in studio debug.

2020-12-12 15:22 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.ServerEmail/OpenBots.Commands.ServerEmail.nuspec
> +    <description>OpenBots command for sending an email message with optional attachment(s) in OpenBots Server.</description>
This description and the one in AssemblyInfo.cs should match

2020-12-12 17:18 UTC, openbots-ff requested changes
Please update the UIImage.cs file as well

2020-12-12 19:28 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.QueueItem/WorkQueueItemCommand.cs
> +										 .ToDictionary(i => i.Key, i => i.Value);
No but I have to refactor queue items for the next version.  I like that suggestion though and will add it to my to do list.

2020-12-12 19:34 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.ServerEmail/OpenBots.Commands.ServerEmail.nuspec
> +    <description>OpenBots command for sending an email message with optional attachment(s) in OpenBots Server.</description>
Done

2020-12-12 19:42 UTC, openbots-ff submitted a review, later dismissed

2020-12-12 23:46 UTC, openbots-ff requested changes

2020-12-12 23:46 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Asset.Tests/UpdateAssetCommandTests.cs
> +            //string outputAsset = "{output}".ConvertUserVariableToString(_engine);
do you still need this comment?

2020-12-12 23:47 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Asset.Tests/UpdateAssetCommandTests.cs
> +            //string outputAsset = "{output}".ConvertUserVariableToString(_engine);
No I'll remove it now

2020-12-12 23:48 UTC, openbots-ff approved these changes

2020-12-13 00:45 UTC, openbots-ch approved these changes

2020-12-13 00:45 UTC, merged