SendServerEmailCommand & QueueItemCommands Unit Tests
OpenBotsAI/OpenBots.Studio pull request #72
Opened 2020-12-22 19:23 UTC by openbots-nc

- Create SendServerEmailCommand unit tests (9)
** Unsure whether to keep no subject and no body unit tests **
- Create WorkQueueItemCommand unit tests (4)
- Create SetQueueItemCommand unit tests (4)
- Create ExtendQueueItemCommand unit tests (2)
- Create AddQueueItemCommand unit tests (5)

2020-12-22 20:49 UTC, openbots-su submitted a review, later dismissed

2020-12-23 20:48 UTC, openbots-ff requested changes

2020-12-23 20:48 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.QueueItem.Tests/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
versions should always match the studio

2020-12-23 20:48 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.ServerEmail.Tests/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
same as above

2020-12-23 20:48 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.ServerEmail/OpenBots.Commands.ServerEmail.nuspec
>      <releaseNotes>https://openbots.ai/category/release-notes/</releaseNotes>
I assume there was a merge conflict here. You want the version in develop, not the one in your branch

2020-12-23 20:48 UTC, openbots-ff commented on OpenBots.sln
> +EndProject
both of these tests projects appear to be in commands. Please move them to commands.tests. File structure in visual studio doesn't always match the actual file directory structure.

2020-12-23 20:48 UTC, openbots-ff commented on OpenBots.sln
>  Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "OpenBots.Engine", "OpenBots.Engine\OpenBots.Engine.csproj", "{ED8F6540-C341-4B5F-8966-26A08E39AF87}"
This is putting the updater project back into the solution. I deleted it so it should stay off.

2020-12-23 20:48 UTC, openbots-ff commented on OpenBots.Updater/OpenBots.Updater.csproj
> +  <Import Project="..\packages\xunit.core.2.4.1\build\xunit.core.props" Condition="Exists('..\packages\xunit.core.2.4.1\build\xunit.core.props')" />
this project shouldn't be here.

2020-12-23 20:48 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.ServerEmail.Tests/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCulture("")]
make sure all the metadata matches the others

2020-12-23 20:48 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.QueueItem/ExtendQueueItemCommand.cs
> +			Common.InitializeDefaultWebProtocol();
this should go below the CommandIcon. It's minor, but it's a consistency thing.

2020-12-23 20:48 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.QueueItem/AddQueueItemCommand.cs
> +			Core.Server.Models.QueueItem queueItem = new Core.Server.Models.QueueItem()
I see you removed the alias. Any particular reason?

2020-12-23 21:33 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.QueueItem.Tests/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
Addressed in commit [https://github.com/OpenBotsAI/OpenBots.Studio/pull/72/commits/7632387fea33a006da47d0522798d2d3e77f42df](url)

2020-12-23 21:33 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.ServerEmail.Tests/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
Addressed in commit [https://github.com/OpenBotsAI/OpenBots.Studio/pull/72/commits/7632387fea33a006da47d0522798d2d3e77f42df](url)

2020-12-23 21:35 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.QueueItem/AddQueueItemCommand.cs
> +			Core.Server.Models.QueueItem queueItem = new Core.Server.Models.QueueItem()
It was creating an error because it was confusing this with the namespace.  Adding it to the code itself resolved the error.

2020-12-23 21:59 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.QueueItem/AddQueueItemCommand.cs
> +			Core.Server.Models.QueueItem queueItem = new Core.Server.Models.QueueItem()
Addressed in [33c93d86a5625ac862a73eae790c826ae9d62da1](https://github.com/OpenBotsAI/OpenBots.Studio/pull/72/commits/33c93d86a5625ac862a73eae790c826ae9d62da1)

2020-12-23 21:59 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.QueueItem/ExtendQueueItemCommand.cs
> +			Common.InitializeDefaultWebProtocol();
Addressed in [33c93d86a5625ac862a73eae790c826ae9d62da1](https://github.com/OpenBotsAI/OpenBots.Studio/pull/72/commits/33c93d86a5625ac862a73eae790c826ae9d62da1)

2020-12-23 22:00 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.ServerEmail.Tests/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCulture("")]
Addressed in [33c93d86a5625ac862a73eae790c826ae9d62da1](https://github.com/OpenBotsAI/OpenBots.Studio/pull/72/commits/33c93d86a5625ac862a73eae790c826ae9d62da1)

2020-12-23 22:00 UTC, openbots-nc commented on OpenBots.Updater/OpenBots.Updater.csproj
> +  <Import Project="..\packages\xunit.core.2.4.1\build\xunit.core.props" Condition="Exists('..\packages\xunit.core.2.4.1\build\xunit.core.props')" />
Addressed in [33c93d86a5625ac862a73eae790c826ae9d62da1](https://github.com/OpenBotsAI/OpenBots.Studio/pull/72/commits/33c93d86a5625ac862a73eae790c826ae9d62da1)

2020-12-23 22:00 UTC, openbots-nc commented on OpenBots.sln
>  Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "OpenBots.Engine", "OpenBots.Engine\OpenBots.Engine.csproj", "{ED8F6540-C341-4B5F-8966-26A08E39AF87}"
Addressed in [33c93d86a5625ac862a73eae790c826ae9d62da1](https://github.com/OpenBotsAI/OpenBots.Studio/pull/72/commits/33c93d86a5625ac862a73eae790c826ae9d62da1)

2020-12-23 22:00 UTC, openbots-nc commented on OpenBots.sln
> +EndProject
Addressed in [33c93d86a5625ac862a73eae790c826ae9d62da1](https://github.com/OpenBotsAI/OpenBots.Studio/pull/72/commits/33c93d86a5625ac862a73eae790c826ae9d62da1)

2020-12-23 22:00 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.ServerEmail/OpenBots.Commands.ServerEmail.nuspec
>      <releaseNotes>https://openbots.ai/category/release-notes/</releaseNotes>
Addressed in [33c93d86a5625ac862a73eae790c826ae9d62da1](https://github.com/OpenBotsAI/OpenBots.Studio/pull/72/commits/33c93d86a5625ac862a73eae790c826ae9d62da1)

2020-12-24 15:20 UTC, openbots-ff submitted a review, later dismissed

2020-12-28 17:21 UTC, openbots-ff approved these changes

2020-12-28 17:22 UTC, openbots-su approved these changes

2020-12-28 17:24 UTC, openbots-ff approved these changes

2020-12-28 17:27 UTC, merged