Email command tests
OpenBotsAI/OpenBots.Studio pull request #73
Opened 2020-12-23 15:25 UTC by openbots-su

Tests for the outlook email commands

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/ForwardOutlookEmailCommandTests.cs
> +            System.Threading.Thread.Sleep(30000);
Does it take the entire 30 seconds or could you possibly use a while loop here to check every 5-10 seconds?  When I added the while loop to my tests it cut down the test time significantly.

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/ForwardOutlookEmailCommandTests.cs
> +            MailItem email = emails[0];
Instead of doing GetOutlookEmailCommand twice, you may be able to use the email variable above as a parameter since it is the same thing.

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/DeleteOutlookEmailCommandTests.cs
> +
Extra line; can be removed

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/MoveCopyOutlookEmailCommandTests.cs
> +            Assert.Equal("toCopy", email.Subject);
Not sure since this is a copy test that you want to assert that the original email still exists?

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/MoveCopyOutlookEmailCommandTests.cs
> +            Assert.Equal("toMove", email.Subject);
With the move test, would you also want to check that the original email doesn't exist?

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/MoveCopyOutlookEmailCommandTests.cs
> +        {
Not sure if it would be simpler to just move back rather than deleting and sending a new one?

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyTitle("OpenBots.Commands.Outlook.Test")]
To go along with the same naming conventions, 'Test' should have an s at the end (for the file name as well)

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyProduct("OpenBots.Commands.Outlook.Test")]
Same comment as above.

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/ReplyToOutlookEmailCommandTests.cs
> +        public void ReplysToOutlookEmail()
Grammatically, this should be 'RepliesToOutlookEmail' or you can just remove the s after 'Reply'

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/ReplyToOutlookEmailCommandTests.cs
> +            System.Threading.Thread.Sleep(30000);
Same comment as previous one: does it take 30 seconds to retrieve or can this be in a while loop?

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/ReplyToOutlookEmailCommandTests.cs
> +        private void resetReplyEmail(AutomationEngineInstance _engine)
The r in 'Reset' should be capital

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/ReplyToOutlookEmailCommandTests.cs
> +            resetReplyEmail(_engine);
The r in 'Reset' should be capital

2020-12-23 19:31 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/SendOutlookEmailCommandTests.cs
> +            System.Threading.Thread.Sleep(30000);
Same as previous comment: does it take 30 seconds to send or can this be done in a while loop?

2020-12-23 20:13 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/ReplyToOutlookEmailCommandTests.cs
> +            resetReplyEmail(_engine);
The reset function is an internal function used by test to reset application state data rather than a test case. For this reason it is in camel case rather than with all words capitalized.

2020-12-23 20:13 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/ReplyToOutlookEmailCommandTests.cs
> +        private void resetReplyEmail(AutomationEngineInstance _engine)
The reset function is an internal function used by test to reset application state data rather than a test case. For this reason it is in camel case rather than with all words capitalized.

2020-12-23 20:30 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/ReplyToOutlookEmailCommandTests.cs
> +        private void resetReplyEmail(AutomationEngineInstance _engine)
Got it, no problem

2020-12-23 20:34 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/ForwardOutlookEmailCommandTests.cs
> +            System.Threading.Thread.Sleep(30000);
File removed

2020-12-23 20:37 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/SendOutlookEmailCommandTests.cs
> +            System.Threading.Thread.Sleep(30000);
Addressed in 018e67d

2020-12-23 20:37 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/ReplyToOutlookEmailCommandTests.cs
> +            System.Threading.Thread.Sleep(30000);
Addressed in 018e67d

2020-12-23 20:38 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/ReplyToOutlookEmailCommandTests.cs
> +        public void ReplysToOutlookEmail()
Addressed in 018e67d

2020-12-23 20:38 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/MoveCopyOutlookEmailCommandTests.cs
> +            Assert.Equal("toCopy", email.Subject);
Addressed in 018e67d

2020-12-23 20:38 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/DeleteOutlookEmailCommandTests.cs
> +
Addressed in 018e67d

2020-12-23 20:53 UTC, openbots-ff requested changes
I noticed that some of the test project/file names end with "Test" and others with "Tests". Please be consistent with one or the other. Please make sure the AssemblyInfo matches this.

2020-12-23 20:53 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Email.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCulture("")]
metadata should match the other tests/commands

2020-12-23 20:53 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Email.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
version should always match the studio

2020-12-23 20:53 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
same as above

2020-12-23 21:03 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
Addressed in 
9b429ce

2020-12-23 21:03 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Email.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
Addressed in 9b429ce

2020-12-23 21:04 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Email.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCulture("")]
Addressed in 4094a52

2020-12-23 21:34 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Email.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCulture("")]
Updated project names and assemblies to the singular "Test" format in 64452c0 and updated the copyright information in 
81c3e0d

2020-12-24 15:04 UTC, openbots-ff approved these changes

2020-12-24 15:55 UTC, openbots-ff approved these changes

2020-12-28 15:01 UTC, openbots-nc commented on OpenBots.Commands.Test/OpenBots.Commands.Outlook.Test/MoveCopyOutlookEmailCommandTests.cs
> +        {
Had conversation as to why the original code was a better option.

2020-12-28 15:01 UTC, openbots-nc approved these changes

2020-12-28 15:15 UTC, merged