Updated and Added Dictionary Commands
OpenBotsAI/OpenBots.Studio pull request #75
Opened 2020-12-24 20:39 UTC by openbots-aw

- Updated dictionary commands
- Added new dictionary commands (GetKeyFromKeyValuePairCommand, GetValueFromKeyValuePairCommand)
- Updated loop collection command to loop through dictionaries
- Added support for dictionary value types (Datatable, MailItem, MimeMessage, IWebElement)
- Updated OpenBots.Core to support dictionary changes

2020-12-24 21:16 UTC, openbots-nc requested changes

2020-12-24 21:16 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Dictionary/CreateDictionaryCommand.cs
> +								throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
DataException

2020-12-24 21:16 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Dictionary/CreateDictionaryCommand.cs
> +								throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
DataException

2020-12-24 21:16 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Dictionary/CreateDictionaryCommand.cs
> +							throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
DataException

2020-12-24 21:16 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Dictionary/CreateDictionaryCommand.cs
> +								throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
DataException

2020-12-24 21:16 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Dictionary/GetDictionaryValueCommand.cs
> +				throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
DataException

2020-12-24 21:16 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Dictionary/GetKeyFromKeyValuePairCommand .cs
> +				throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
DataException

2020-12-24 21:16 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Dictionary/GetValueFromKeyValuePairCommand.cs
> +				throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
DataException

2020-12-24 21:16 UTC, openbots-nc commented on OpenBots.Commands/OpenBots.Commands.Loop/LoopCollectionCommand.cs
> +            }
Fix indentation here

2020-12-24 21:16 UTC, openbots-nc commented on OpenBots.Core/Utilities/CommonUtilities/VariableMethods.cs
> +                                throw new Exception("Only use of key and value is allowed using dot operater with keyvaluepair is allowed");
DataException

2020-12-27 23:44 UTC, openbots-ff requested changes

2020-12-27 23:44 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Dictionary/GetKeyFromKeyValuePairCommand .cs
> +		[DisplayName("Output Value Variable")]
```suggestion
		[DisplayName("Output Key Variable")]
```

2020-12-27 23:44 UTC, openbots-ff commented on OpenBots.Core/Utilities/CommonUtilities/StringMethods.cs
>                      case string b when b.Contains("System.Collections.Generic.Dictionary`2[[System.String") && b.Contains("],[System.Object"):
It looks like you kept a generic object for dictionaries here but you were more specific with the keyvalue pairs. Did you test whether they both render properly in the debug pane/show message window? Please keep in mind that this Dictionary<string, object> type was created for the WorkQueueItem command and that needs to still render correctly after all these changes.

2020-12-28 16:58 UTC, openbots-ab reviewed
Please add the tags for the new commands in .nuspec file of this project.

2021-01-04 13:26 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/AddDictionaryItemCommand.cs
> +					throw new Exception("Dictionary type Not Supported");
Done.

2021-01-04 13:26 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/AddDictionaryItemCommand.cs
> +							throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
Done.

2021-01-04 13:26 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/AddDictionaryItemCommand.cs
> +							throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
Done.

2021-01-04 13:27 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/AddDictionaryItemCommand.cs
> +							throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
Done.

2021-01-04 13:27 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/AddDictionaryItemCommand.cs
> +				throw new Exception("Attempted to add data to a variable, but the variable was not found. Enclose variables within braces, ex. {vVariable}");
Done.

2021-01-04 13:27 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/GetDictionaryValueCommand.cs
> +				throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
Done.

2021-01-04 13:27 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/GetKeyFromKeyValuePairCommand .cs
> +				throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
Done.

2021-01-04 13:27 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/GetValueFromKeyValuePairCommand.cs
> +				throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
Done.

2021-01-04 13:27 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Loop/LoopCollectionCommand.cs
> +            }
Done.

2021-01-04 13:27 UTC, openbots-aw commented on OpenBots.Core/Utilities/CommonUtilities/VariableMethods.cs
> +                                throw new Exception("Only use of key and value is allowed using dot operater with keyvaluepair is allowed");
Done.

2021-01-04 13:28 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/GetKeyFromKeyValuePairCommand .cs
> +		[DisplayName("Output Value Variable")]
Done.

2021-01-04 13:32 UTC, openbots-aw commented on OpenBots.Core/Utilities/CommonUtilities/StringMethods.cs
>                      case string b when b.Contains("System.Collections.Generic.Dictionary`2[[System.String") && b.Contains("],[System.Object"):
I have added all supported types, and at the end I have included the Dictionary<string, object> in StringMethods.cs. I have tested rendering in debug pane/show message for all dictionary types.

2021-01-04 14:50 UTC, openbots-ff requested changes

2021-01-04 14:50 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Dictionary/OpenBots.Commands.Dictionary.nuspec
> +    <tags>OpenBots Studio Dictionary Commands AddDictionaryItem CreateDictionary GetDictionaryValue GetKeyFromKeyValuePairCommand GetValueFromKeyValuePairCommand</tags>
```suggestion
    <tags>OpenBots Studio Dictionary Commands AddDictionaryItem CreateDictionary GetDictionaryValue GetKeyFromKeyValuePair GetValueFromKeyValuePair</tags>
```

2021-01-08 15:01 UTC, openbots-ff requested changes

2021-01-08 15:01 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Dictionary/UpdateDictionaryValueCommand.cs
> +		public string v_Key { get; set; }
Could you swap the order of key and value here, and in the render method?

2021-01-11 07:18 UTC, openbots-ff requested changes

2021-01-11 07:18 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.Dictionary/RemoveDictionaryValueCommand.cs
> +			return base.GetDisplayValue() + $" [Remove Value from Dictionary '{v_DictionaryName}' at Value '{v_Key}']";
```suggestion
			return base.GetDisplayValue() + $" [Remove Value from Dictionary '{v_DictionaryName}' at Key '{v_Key}']";
```

2021-01-11 12:23 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/UpdateDictionaryValueCommand.cs
> +		public string v_Key { get; set; }
Done.

2021-01-11 18:02 UTC, openbots-ff approved these changes

2021-01-15 12:09 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/CreateDictionaryCommand.cs
> +								throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
Done.

2021-01-15 12:09 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/CreateDictionaryCommand.cs
> +								throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
Done

2021-01-15 12:09 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/CreateDictionaryCommand.cs
> +							throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
Done.

2021-01-15 12:09 UTC, openbots-aw commented on OpenBots.Commands/OpenBots.Commands.Dictionary/CreateDictionaryCommand.cs
> +								throw new Exception("Invalid dictionary value type, please provide valid dictionary value type.");
Done.

2021-01-16 08:14 UTC, openbots-ff approved these changes

2021-01-19 14:40 UTC, openbots-ab approved these changes

2021-01-19 17:32 UTC, openbots-ch approved these changes

2021-01-19 17:34 UTC, openbots-nc approved these changes

2021-01-19 17:35 UTC, merged