Move credential storage into project
OpenBotsAI/OpenBots.Studio pull request #77
Opened 2020-12-28 17:19 UTC by openbots-su

Credential text files are provided in the project but do not contain true values and must be updated locally after fetching.

2020-12-28 17:30 UTC, openbots-ff requested changes

2020-12-28 17:30 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Credential.Tests/GetCredentialCommandTests.cs
> +            string projectDirectory = Directory.GetParent(Environment.CurrentDirectory).Parent.Parent.Parent.FullName;
You can just just the resources directly instead of hard accessing the paths. Take a look at the HTMLInputCommand, line 46

2020-12-30 15:46 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Credential.Tests/GetCredentialCommandTests.cs
> +            string projectDirectory = Directory.GetParent(Environment.CurrentDirectory).Parent.Parent.Parent.FullName;
Addressed in d827eb0

2020-12-30 15:48 UTC, openbots-ff approved these changes

2020-12-30 16:16 UTC, openbots-nc approved these changes

2020-12-30 16:17 UTC, merged