File command tests
OpenBotsAI/OpenBots.Studio pull request #79
Opened 2021-01-05 13:48 UTC by openbots-su

2021-01-05 15:06 UTC, openbots-ff requested changes

2021-01-05 15:06 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.File/MoveCopyFileCommand.cs
> +				throw new ArgumentException(String.Format("File {0} does not exist", sourceFile));
Do we want to use ArgumentException as a catch all? Because there's also a FileNotFoundException that could be used here.

2021-01-05 15:06 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.File/CompressFilesCommand.cs
> +				throw new ArgumentException(String.Format("{0} is a file when it should be a directory", vSourceDirectoryPathOrigin));
```suggestion
				throw new ArgumentException($"{vSourceDirectoryPathOrigin} is a file when it should be a directory");
```

2021-01-05 15:06 UTC, openbots-ff commented on OpenBots.Commands/OpenBots.Commands.File/CompressFilesCommand.cs
> +				throw new ArgumentException(String.Format("{0} is a file when it should be a directory", vSourceDirectoryPathOrigin));
Conventionally we use this method for string formatting. Functionally it makes no difference, but this is usually a bit cleaner I think.

2021-01-05 15:23 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.File/CompressFilesCommand.cs
> +            if (System.IO.File.Exists(vSourceDirectoryPathOrigin))
Addressed in 
13d651c

2021-01-05 15:52 UTC, openbots-su commented on OpenBots.Commands/OpenBots.Commands.File/MoveCopyFileCommand.cs
> +				throw new ArgumentException(String.Format("File {0} does not exist", sourceFile));
Addressed in 9162ec5

2021-01-05 16:37 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.File.Test/ExtractFilesCommandTests.cs
> +            _engine = new AutomationEngineInstance(null);
Addressed in 60f879a

2021-01-05 16:38 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.File.Test/ExtractFilesCommandTests.cs
> +            outputPath.StoreInUserVariable(_engine, "{outputPath}");
Addressed in 60f879a

2021-01-05 16:38 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.File.Test/CompressFilesCommandTests.cs
> +            outputPath.StoreInUserVariable(_engine, "{outputPath}");
Addressed in 60f879a

2021-01-05 22:16 UTC, openbots-ff approved these changes

2021-01-06 07:13 UTC, openbots-ch approved these changes

2021-01-06 07:13 UTC, merged