Folder command tests
OpenBotsAI/OpenBots.Studio pull request #84
Opened 2021-01-07 14:30 UTC by openbots-su

2021-01-07 17:04 UTC, openbots-nc approved these changes

2021-01-11 07:08 UTC, openbots-ff requested changes

2021-01-11 07:08 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Folder.Test/DeleteFolderCommandTests.cs
> +            inputPath.StoreInUserVariable(_engine, "{inputPath}");
how are you handling the creation/reset of the folder that you're deleting?

2021-01-11 08:02 UTC, openbots-ch requested changes

2021-01-11 14:41 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Folder.Test/DeleteFolderCommandTests.cs
> +            inputPath.StoreInUserVariable(_engine, "{inputPath}");
The directory was being re-created on line 30. I have also updated it to reset the contents of the folder in ab4dc86.

2021-01-11 15:59 UTC, openbots-ch approved these changes

2021-01-11 18:03 UTC, openbots-ff approved these changes

2021-01-11 18:04 UTC, merged