Engine command tests
OpenBotsAI/OpenBots.Studio pull request #93
Opened 2021-01-12 14:43 UTC by openbots-su

2021-01-12 22:06 UTC, openbots-ff requested changes

2021-01-12 22:06 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Engine.Test/SetEnginePreferenceCommandTests.cs
> +            _setEnginePreference.RunCommand(_engine);
This as well. Disabling automation calculations means that doing something like "1 + 1" in set variable command would return "1 + 1" instead of "2".

2021-01-12 22:06 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Engine.Test/StopwatchCommandTests.cs
> +            System.Threading.Thread.Sleep(1000);
is it possible to trim this to Thread.Sleep(1000); ?

2021-01-13 15:26 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Engine.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.2.1.0")]
Addressed in a5019f8

2021-01-13 15:26 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Engine.Test/ErrorHandlingCommandTests.cs
> +            _errorHandling.RunCommand(_engine);
Addressed in ede2a5c

2021-01-13 17:01 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Engine.Test/SetEngineDelayCommandTests.cs
> +            _setEngineDelay.RunCommand(_engine);
Addressed in 504c64b

2021-01-13 17:59 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Engine.Test/SetEnginePreferenceCommandTests.cs
> +            _setEnginePreference.RunCommand(_engine);
Addressed in 32981db

2021-01-13 18:00 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Engine.Test/StopwatchCommandTests.cs
> +            System.Threading.Thread.Sleep(1000);
Addressed in 0b06a07

2021-01-15 02:53 UTC, openbots-ff approved these changes

2021-01-15 02:53 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Engine.Test/ErrorHandlingCommandTests.cs
>          [InlineData("Stop Processing")]
Isn't there a continue option as well?

2021-01-15 14:03 UTC, openbots-ch approved these changes

2021-01-15 14:03 UTC, merged