Switch command tests
OpenBotsAI/OpenBots.Studio pull request #94
Opened 2021-01-14 21:53 UTC by openbots-su

2021-01-15 03:14 UTC, openbots-ff requested changes

2021-01-15 03:14 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Switch.Test/SwitchCommandTests.cs
> +            _engine.AutomationEngineContext.Variables.Add(case1);
I'm having a little trouble following your naming conventions here. Could you make these ScriptVariable names either more descriptive, or add a comment explaining what each one is for?

2021-01-15 18:00 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Switch.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.0.0.0")]
Addressed in 611e9ce

2021-01-15 18:00 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Switch.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2021")]
Addressed in 611e9ce

2021-01-15 18:01 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Task.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
Addressed in 611e9ce
I plan to also include the task test in this PR once it is completed. I will also be updating old tests to use the new variable creation scheme.

2021-01-15 18:01 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Switch.Test/SwitchCommandTests.cs
> +            _engine.AutomationEngineContext.Variables.Add(case1);
Renamed in 824a3b0

2021-01-16 08:07 UTC, openbots-ff requested changes

2021-01-16 08:07 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Switch.Test/SwitchCommandTests.cs
> +            ScriptVariable caseInput = new ScriptVariable();
You're not using the createtestvariable method here

2021-01-16 08:10 UTC, openbots-ff requested changes

2021-01-16 08:10 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Switch.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("1.0.0.0")]
You changed it in Task but not in Switch

2021-01-16 08:10 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Switch.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2021")]
You changed it in Task but not in Switch

2021-01-16 08:11 UTC, openbots-ff commented on OpenBots.Commands.Test/OpenBots.Commands.Task.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
You also have script files in the resources though. Do you intend to keep those?

2021-01-16 08:12 UTC, openbots-ff commented
Please resolve the merge conflicts

2021-01-25 14:56 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Switch.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright ©  2021")]
Addressed as of 0271f65

2021-01-25 14:56 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Task.Test/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
Removed unused resources as of 0271f65

2021-01-25 14:56 UTC, openbots-su commented on OpenBots.Commands.Test/OpenBots.Commands.Switch.Test/SwitchCommandTests.cs
> +            ScriptVariable caseInput = new ScriptVariable();
Updated as of 0271f65

2021-01-25 15:53 UTC, openbots-ff approved these changes

2021-01-26 14:41 UTC, openbots-ch approved these changes

2021-01-26 14:41 UTC, merged